### ISSUE TITLE
Upload 1 ­- Describe Your Work Page

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/umrdr#108]
1. All attribute titles need to be bold. (Not just Required Attributes)
2. Move help text underneath the attribute title and above the text field.
3.Discipline Attribute (dropdown) needs ability to add another discipline ('add discipline' button)

**Comment by respinos** [comment]
#2 fixed in b7b9194ce75e79f6a94c4e2235a07b9b860737c9

**Comment by respinos** [comment]
Labels are all bolded after nightly UX work by @justcolin.
