### ISSUE TITLE
Upload 2 -­ Upload your Data

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/umrdr#109]
1. Left Align table header title, ‘Attribute Name’
2. Left Align table header title, ‘Values’
3. Insert paragraph break below the text, 'This Generic Work has no files associated with
it. You can add one using the 'Attach a File' button below.'
4. Remove Export EndNote, Export Zotero, Export Mendeley buttons in Upload Process.

**Comment by respinos** [comment]
![image](https://cloud.githubusercontent.com/assets/537867/13261800/bfd601e0-da2f-11e5-835a-002423496163.png)

Does this address the spacing issues of #3?

**Comment by respinos** [comment]
@bnhowell - can you clarify about #4. That row of buttons don't relate to the upload files area (specifically).

**Comment by justcolin** [comment]
@respinos Are you still working on these issues?

**Comment by bnhowell** [comment]
@respinos - #3 solution you have above looks good. Regarding #4, The row of buttons in the lower left hand corner of the upload page (Remove Export EndNote, Export Zotero, Export Mendeley) are not related to any upload files tasks. IT would be great to remove these if possible under current resource constraints.

**Comment by respinos** [comment]
Was waiting for @bnhowell comments: all that remains is #4, and style changes for #1 and #2.

**Comment by justcolin** [comment]
@bnhowell: Update on this? (See Roger's comments)

**Comment by grosscol** [comment]
Split out the fourth item into #221.  Closing the first three.
