### ISSUE TITLE
Upload 3 ­Upload Confirmation 

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/umrdr#110]
1. A Notification needs to appear confirming the upload and work: 'Thank you for depositing your work! You will receive an email confirming your deposit in a few minutes. Your New DOI will be available within 24 hrs.’
2. The second section of this notification (paragraph break) should read, ‘A few things to remember about your new DOI: You have 24 hrs to make changes after you deposit, After 24 hrs your work cannot be edited)

**Comment by justcolin** [comment]
@respinos: Is this issue good to close after PR #136 ?

**Comment by respinos** [comment]
#136 addresses (1), but not (2).

**Comment by grosscol** [comment]
Needs to be separate issues.
