### ISSUE TITLE
Work ­- Edit Work Page

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/umrdr#111]
1. The current help text Under the Page Header ‘Manage Your Work’ needs to be removed.
2. We need to write copy warning users: It is not possible to edit the work and keep the same DOI. Editing the work metadata or files associated with it will result in a new DOI.’

**Comment by respinos** [comment]
#1 is handled by commit df8ad1704d47f78d815870b0b22026f9d2ee86bd

**Comment by grosscol** [comment]
This needs to be split into separate issues.

**Comment by amyneeser** [comment]
#2 is priority

**Comment by justcolin** [comment]
@respinos: Can you take a look at this priority issue?

**Comment by respinos** [comment]
Looking into it. @amyneeser, @justcolin -- should the contact be by way of the contact form?

**Comment by amyneeser** [comment]
Yes, please direct to the contact form.

**Comment by respinos** [comment]
@amyneeser, @justcolin --- This would appear **after** a contributor minted a DOI on a work and then tried to edit it:

![image](https://cloud.githubusercontent.com/assets/537867/13580432/3c740752-e470-11e5-86d5-ab19c3c6a82b.png)

Should a similar warning be near the "Mint DOI" action?

![image](https://cloud.githubusercontent.com/assets/537867/13580516/a83b1a66-e470-11e5-893d-af60ad1ec4e6.png)

**Comment by amyneeser** [comment]
Yes!


On Mon, Mar 7, 2016 at 2:27 PM, respinos <notifications@github.com> wrote:

> @amyneeser <https://github.com/amyneeser>, @justcolin
> <https://github.com/justcolin> --- This would appear *after* a
> contributor minted a DOI on a work and then tried to edit it:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/537867/13580432/3c740752-e470-11e5-86d5-ab19c3c6a82b.png>
>
> Should a similar warning be near the "Mint DOI" action?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/537867/13580516/a83b1a66-e470-11e5-893d-af60ad1ec4e6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlibrary/umrdr/issues/111#issuecomment-193410080>.
>



-- 
Amy Neeser
Research Data Curation Librarian
University of Michigan Libraries
260E Hatcher Graduate Library South
734-764-2203 | aneeser@umich.edu
ORCID: 0000-0003-2523-5079 <http://orcid.org/0000-0003-2523-5079>

**Comment by justcolin** [comment]
@respinos: Can you put programatic focus on that element when it comes up?

**Comment by justcolin** [comment]
That will make sure it is noticed by people and help screen reader users.

**Comment by respinos** [comment]
@justcolin @grosscol @amyneeser - following the "contact deep blue" from the DOI warning sets up the contact form to be about the DOI message:

![doi_warning](https://cloud.githubusercontent.com/assets/537867/13610387/7417bab2-e52b-11e5-8f3b-7710db9ff697.gif)

**Comment by justcolin** [comment]
@respinos Looks good to me. Also: __*what is this GIF wizardry!?*__

**Comment by respinos** [comment]
- QuickTime Player capture screen region
- `ffmpeg -i in.mov -vf scale=800:-1 -r 24 -f image2pipe -vcodec ppm - | convert -delay 5 -layers Optimize -loop 0 - out.gif` via one of the responses in [this gist](https://gist.github.com/dergachev/4627207)

**Comment by justcolin** [comment]
@respinos: Thank you got that magical incantation.

**Comment by njaffer** [comment]
done
