### ISSUE TITLE
My Works page

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/umrdr#113]
1. Remove “Upload” button
2. “Select Action” dropdown hidden within scrolling table/box.
3. Add label next to check box above gear
4. Remove gear icon/button for sorting lists

Annotated Screenshot of My Works page in InVision:
https://invis.io/JM656ZC49

**Comment by respinos** [comment]
#2 is due to bootstrap's [responsive tables](http://getbootstrap.com/css/#tables-responsive).

**Comment by justcolin** [comment]
Addressed with upcoming set of commits from the new_interface branch
