### ISSUE TITLE
Help page missing?

### ISSUE THREAD

**Issue by justcolin** [mlibrary/umrdr#127]
@grosscol / @respinos: In my dev environment going to the help page now results in `ActionView::MissingTemplate in Static#help`.

**Comment by justcolin** [comment]
Same thing for about: `ActionView::MissingTemplate in Static#about`

**Comment by justcolin** [comment]
Both of these issues are also happening on the stable dev site.

**Comment by respinos** [comment]
The homepage.html.erb layout is used by both help/static pages and the homepage; I added a jumbo region for the "home_header" content.
