### ISSUE TITLE
User should be able to search on keywords from show work page

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#134]
When a user clicks on the keywords in show work, it gives an error 'tag' not found. The problem is down to CC, where tag is defined as 'tags' in solr:

Few options can be done later to make it a link:
override: https://github.com/projecthydra-labs/curation_concerns/blob/bab2f05e1d1dbbec8366dbf7eace94cb1e49a534/app/renderers/curation_concerns/attribute_renderer.rb

or this: https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/solr_document_behavior.rb#L100

Related PR in Sufia: projecthydra/sufia#1561

**Comment by respinos** [comment]
The links aren't for editing the keywords --- they're for searching works by that keyword.

**Comment by njaffer** [comment]
@respinos: Should we close this? I can search on the keywords from Work Show page
