### ISSUE TITLE
Upload 1 ­- Describe Your Work Page - Method Attribute

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/umrdr#141]
I was verifying the required fields in our Deep Blue Data policy documents here:

https://docs.google.com/a/umich.edu/document/d/1Qr_3zGPvLFhlgCcz-DpgJ-3EpCj0Lii96DOv5gerFa0/edit?usp=sharing

and 

https://docs.google.com/a/umich.edu/document/d/19IjdRLuqrkdroJ-IM7mVcgVkZntYvgggu-cRw7rgh9M/edit?usp=sharing

The Method attribute needs to be included as a required and free text entry field.
Here is the copy:

Title: **Method** Required
Help Text: The way the dataset was collected (equipment used for sensing, survey methodology, etc.)

**Comment by respinos** [comment]
Could this be a kind of "Accrual Method"? http://dublincore.org/usage/terms/history/#accrualMethod-003

**Comment by grosscol** [comment]
When queried, the metadata librarian (mcarruth) had the following to say:

> The Dublin Core Accrual Method is intended to describe accruals that are more bibliographic in nature, or resource-based, rather than to outline a research methodology.  
> 
> http://dublincore.org/groups/collections/accrual-method/
> 
> That said, Dublin Core is pretty lax when it comes to dictating how elements are meant to be used.  Another possibility is to go the route that ICPSR has and use the Data Documentation Initiative "Methodology" element.
> 
> http://www.ddialliance.org/Specification/DDI-Lifecycle/3.2/XMLSchema/FieldLevelDocumentation/

direct link to methodology:
http://www.ddialliance.org/Specification/DDI-Lifecycle/3.2/XMLSchema/FieldLevelDocumentation/schemas/datacollection_xsd/elements/DataCollectionMethodology.html

If this is not available in RDF::Vocab, we can specify the URL to the element and put a ticket in to add the vocab to RDF::Vocab (assuming we have someone with time to do so)

**Comment by grosscol** [comment]
Closed by #153
