### ISSUE TITLE
MVP: User-managed collections for grouping files

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#15]
Depositor can aggregate deposited files into logical groups.

**Comment by njaffer** [comment]
@skorner , @grosscol: what is a logical group? Is this feature still a priority?

**Comment by skorner** [comment]
This is referencing the straight-up Sufia 6 (pre-PCDM and the notion of 'works') collection designation functionality in Sufia 6. Has that collection functionality simply carried over into Sufia 7 with 'generic works' replacing 'files' as the collection building block?

**Comment by njaffer** [comment]
In Sufia 7, Collections have Works, and Works have Files. Does that mean a Work is a logical group of files or a collection is a logical group of works?

**Comment by grosscol** [comment]
A Collection members can be collections and works.  Works members can be works (although there isn't ui support for this yet) and FileSets (files).

**Comment by skorner** [comment]
So it sounds like the PCDM evolution of this MVP item is simply "user managed collections for grouping works." The fact that collection members can be collections and works is a nice bonus.

**Comment by njaffer** [comment]
@grosscol: Can a collection member be a collection? The current UI does not have any option of adding a collection as a member of an existing collection. Can this be done via console or batch?

**Comment by grosscol** [comment]
Correct, there is not currently a ui to expose the functionality.

**Comment by njaffer** [comment]
The basic functionality of creating grouped work exists in Sufia 7
