### ISSUE TITLE
Test browse_everything gem integration for Google Drive

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#154]
The code is integrated in the codebase, the Google Drive gives the error of "authorization code not found". Check the code for generating refresh_token

**Comment by jrcarlso9** [comment]
Add M+Box to this as well.

**Comment by njaffer** [comment]
waiting for staging

**Comment by grosscol** [comment]
Per @justcolin the functionality of the Google Drive integration is abysmally slow in some cases.  Closing this ticket as that problem makes this a "wont fix"
