### ISSUE TITLE
Transfer work: Depositor field should not change

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#159]
When a work is transferred ownership, the new owner receives the notification, and can accept the work. There is no agreement to agree to when accepting the transferred work. The depositor field should not be updated, instead only ownership should be changed.

Possible solutions: The user must agree to work ownership agreement before accepting the work or keep the depositor same as the original owner and change the owner field only.

**Comment by njaffer** [comment]
There are 3 options in transfer work, Confirm all the options work as expected:

<img width="916" alt="screen shot 2016-02-28 at 12 11 04 pm" src="https://cloud.githubusercontent.com/assets/12487929/13380550/66bacc7e-de14-11e5-966b-2786ea277bbc.png">

**Comment by njaffer** [comment]
keep the depositor field as the original  depositor and use owner  field for the recipient of the transferred work

**Comment by grosscol** [comment]
This issue is part of a bigger problem upstream.  Owner and depositor needs to be disambiguated upstream.
