### ISSUE TITLE
Restore & Test Proxy User functionality

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#169]
The proxy user plugin is removed from dashboard. Check the functionality for both work and files

**Comment by njaffer** [comment]
<img width="1128" alt="screen shot 2016-04-07 at 2 14 20 pm" src="https://cloud.githubusercontent.com/assets/12487929/14362177/664af18e-fccc-11e5-9c4f-362cb30af97c.png">
<img width="873" alt="screen shot 2016-04-07 at 2 14 48 pm" src="https://cloud.githubusercontent.com/assets/12487929/14362189/6bc46a8c-fccc-11e5-86f3-7c702cc4a51e.png">

**Comment by justcolin** [comment]
@njaffer: Has this been marked as UI because the rest of the code is tested and good to go, but the interface needs polish?

**Comment by njaffer** [comment]
@justcolin : Yes!

**Comment by njaffer** [comment]
done
