### ISSUE TITLE
Responsive, fluid, Bootstrap 3-based UI

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#17]
The user interfaces (for depositors, admins, and especially users) will be responsive and meet the library's minimum accessibility guidelines.

**Comment by skorner** [comment]
As titled in the MVP document, this was a placeholder long before we knew what our plan was. @justcolin @bnhowell @treevore Can you update this issue (title, description, assignment, etc) to reflect your work? Also, feel free to leverage the associated waffle board to coordinate and/or track progress, if that's helpful.

**Comment by Treevore** [comment]
Colin and I met yesterday about working towards getting a v1 of the UI elements in place this week. I will use this issue as a general status. I will try to track it in this spreadsheet https://docs.google.com/spreadsheets/d/1HIjmX48QWWp9q63n9yqyWMRUtSlklFA0zIx_Cyjhw1k/edit?ts=56b8e171#gid=0

**Comment by grosscol** [comment]
@Treevore Why have a separate spreadsheet for tracking issues when the repository has an issue tracker already?

**Comment by njaffer** [comment]
@Treevore, thank you for putting all the tasks in the excel sheet. It looks great! @grosscol: We are tracking the Design/UI work in the excel sheet, because we did not create issues on the github.

**Comment by grosscol** [comment]
I do not see a compelling reason to have two separate issue trackers.

**Comment by Treevore** [comment]
I will do my best to update this issue as well for those who use Github.

**Comment by njaffer** [comment]
We have created other actionable tickets for UI
