### ISSUE TITLE
Upload 1 ­- Describe Your Work Page - Contributor (Depositor) Attribute

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/umrdr#179]
The Contributor (Depositor) is confusing. @respinos states that the depositor is an attribute which the system generates automatically and doesn't need to be entered, however, @njaffer says that the attribute (within the Sufia Community) is related to additional persons outside the 'Creators' who have contributed to the data within the work. (e.g., interns, other non-authors/creators). 

- At a minimum, I recommend that we remove the (Depositor) text from Contributor attribute title and rewrite the help text to define the attribute more clearly. Something like: ('Persons or organizations outside the Creator role who have contributed to the work in this dataset') 

- I also recommend that the Contributor field be repositioned in the form below the required attributes (underneath the Creative Commons License drop down field). 

- If our use for this attribute is to describe the depositor (which is automatically generated by the system and viewable in the work metadata post upload) I would love to see this field removed.

**Comment by njaffer** [comment]
TODO: Remove the (Depositor) text from Contributor attribute title and rewrite the help text to define the attribute more clearly. Something like: ('Persons or organizations outside the Creator role who have contributed to the work in this dataset')

**Comment by gordonleacock** [comment]
Perhaps rename "Contributor" to "Contributors".
