### ISSUE TITLE
MVP: Proxy deposit and transfers of ownership

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#18]
Researchers can assign proxy authority to one or more specific individuals for managing deposits. When a proxy takes an action in the repository, email confirmations are sent to the proxy and to the researcher.

**Comment by gordonleacock** [comment]
On the test site, njaffer and I both have accounts but can't proxy each other.

**Comment by gordonleacock** [comment]
However, transfer of ownership appears to be working.

**Comment by gordonleacock** [comment]
Regarding proxy, the part that is failing is the widget for looking up other users with whom to proxy or to share a work.

**Comment by njaffer** [comment]
In Sufia 7, the proxy user submission was not working, which was due to a bug in Curation Concerns. I have submitted the PR for CC: https://github.com/projecthydra-labs/curation_concerns/pull/600

Once the PR is merged, the functionality should be working

**Comment by njaffer** [comment]
Assigning proxy user and uploading on behalf of  is working. The email is NOT sent to the proxy and to the researcher.
