### ISSUE TITLE
Remove cosign config from application

### ISSUE THREAD

**Issue by aelkiss** [mlibrary/umrdr#184]
The Cosign configuration should (mostly) not need to live in the application.
- Change the 'login' button to go to `/data/dashboard` (the current 'login' landing page)
- Set `CosignAllowPublicAccess off` for `/data/dashboard` in the Apache configuration
- Remove the following configuration keys - Apache `mod_cosign` will automatically redirect the user as needed.
  - `config.cosign_service`
  - `config.cosign_login_redirect`
  - `config.login_url`
- Retain `config.logout_url` - `mod_cosign` has no logout functionality.

**Comment by aelkiss** [comment]
We should also set `CosignAllowPublicAccess off` for any paths that should not be accessible unless the user is logged in, e.g. `/works/edit/`

**Comment by aelkiss** [comment]
The login button can continue going to `/data/login`; that is path with `CosignAllowPublicAcces off`.

Devise/Warden already take care of protecting non-public pages via `authorize_user!` - that redirects users to `/data/login` if they are not already logged in.

`/data/login` after returning from Cosign then take cares of redirecting the user to `/data/dashboard` or whatever other non-public page the user tried to access. Devise stores the path the user came from in the session.

**Comment by njaffer** [comment]
Done in development - will close after it goes to production
