### ISSUE TITLE
File Formats & Preservation page

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#185]
The link at the bottom of the page, "Review our Preservation Policy for additional details" links to itself. I think it should go to the Policy and Terms of Use page, but can it jump down to the preservation policy (section 4)?

**Comment by heidisb** [comment]
Totally my miss there. The link should go to:

/data/agreement#preservation_policy

**Comment by justcolin** [comment]
I will update this and get a release pushed out soon.

**Comment by justcolin** [comment]
The close button is too close to the comment button...
