### ISSUE TITLE
Cannot update profile picture

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#186]
The user cannot edit the profile picture, facebook, twitter or ORCID.

Also delete proxy user from user profile edit page

**Comment by amyneeser** [comment]
Remove Facebook.

**Comment by grosscol** [comment]
Is deleting proxy users from the user profile edit page related to the editing issue?  If not, please separate the issues into two separate tickets.

**Comment by njaffer** [comment]
@grosscol: Agreed, creating a separate issue
