### ISSUE TITLE
Add search for depositors by name function

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/umrdr#189]
Currently, Deep Blue Data depositors can be searched by uniqname only within the profile view. Clicking a depositor's listing only shows recent activity.
Desired behavior is: 
1. Allow users to search for depositors by MCommunity name (a combination of First, Last, etc.). 
2. Show depositors in a paginated view that can take users to a listing of depositor's works.
3. Move search function access out of the profile page to a more prominent position (dashboard?).

Hmmm, maybe this should be more that one issue :-)

**Comment by grosscol** [comment]
Too broad.  Not actionable.  The fields are already searchable by text.  Pulling data from LDAP is another issue.
