### ISSUE TITLE
MVP: Tombstoning of deleted items

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#19]
If an item deposited to the repository is deleted or suppressed, its URI and DOI redirect to a page explaining that the item is no longer avaialble. No specific reason is necessarily cited. Site admins must have a specific explanation of why the object is no longer available.

**Comment by grosscol** [comment]
This is a feature that needs to differ from the innately provided tombstoning from Fedora. The cases for a work where it has either not been indexed or has not had a doi published are simple:
* If work has not been indexed, remove content and work.  Fedora tombstone will prevent id from being reused.
* If work has been indexed but no DOI published, remove content and work.  Remove indexed content.

Removing works that have had a DOI published should not be permitted by the user.  If/when one has to be removed, it will not be accomplished through the public facing UI.  Questions to be addressed should be:
* keep content?
* message to put in description attribute detailing what was removed and why.
* Removal of content from index.
* Marking object as `do_not_index`

**Comment by skorner** [comment]
It is correct that tombstones were an MVP feature. A year ago that looked to be on the community roadmap for the following year (maybe with some help from us), but with all the effort on PCDM that did not pan out. This should move to 2.0 and we and the community can revisit it later. Besides, it's tradition for all our repository services to launch w/o tombstone capability and have it implemented at a later date!

**Comment by njaffer** [comment]
@skorner: moved to 2.0

**Comment by njaffer** [comment]
![screen shot 2017-01-05 at 10 26 39 am](https://cloud.githubusercontent.com/assets/12487929/21685956/866b107a-d331-11e6-8c92-55039cd33ce2.png)

**Comment by njaffer** [comment]
@amyneeser: Please supply the language for tombstone page

**Comment by amyneeser** [comment]
This item is no longer available in Deep Blue Data due to one of the following reasons:

- It was deleted at the request of the rights holder
- It was found not to comply with Deep Blue Data’s Submission and Deposit Policy

**Comment by njaffer** [comment]
Fulcrum team is working on tombstone as well: https://github.com/mlibrary/heliotrope/issues/994

**Comment by amyneeser** [comment]
For hiding vs. deleting files: please hide instead of deleting files when a tombstone is needed. 

For the question of when to delete vs. tombstone: if the item is not available anywhere else create a tombstone; if it is available elsewhere and has DOI we delete and point DOI to new place; if it is available elsewhere and no DOI, we need a redirect page (not tombstone).

**Comment by blancoj** [comment]
After my discussion with Jake, these are the requirements we came up with:
1.  Offer admin 3 reasons for tombstone ( just like in DB Doc )
    - Removed from view by legal order.
    - Removed from view by the University.
    - Removed from view at request of the author.
2.  Only admin can tombstone a work.
3. No one should ever discover the tombstoned work, unless the user has the url.
4. The tombstone page of the work should show the reason for tombstone selected by the admin.

**Comment by mutanthumb** [comment]
Per yesterday's Stand Up meeting... be sure to capture the name (account) and date of who did the tombstone. Here is an example of the provenance metadata from Deep Blue docs:
Item withdrawn by Jose Blanco (blancoj@umich.edu) on 2006-11-27T14:56:21Z
Item was in collections:
Libraries, University of Michigan (ID: 17)
 -- 1 bitstream(s): "TestDeepBlue.txt"

**Comment by blancoj** [comment]
@njaffer I have not addressed this last comment by @mutanthumb in my pr, this could be a different issue so we can merge that pr.  I wont have time for it until I finish the Samvera Sprint.  Thanks!
