### ISSUE TITLE
Mobile website: About Page - fix left side bar text

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#194]
The text from left side bar is overlapping with the main text:
![img_0534](https://cloud.githubusercontent.com/assets/12487929/13474677/24ac4d1e-e08d-11e5-8ad9-68b9c6440471.PNG)

**Comment by justcolin** [comment]
There is a commit to fix this, should be pushed out soon.

**Comment by njaffer** [comment]
Thanks @justcolin , we can close it after the commit is merged and tested.

**Comment by justcolin** [comment]
Fixed by #195

**Comment by justcolin** [comment]
There are still problems on iOS. I will investigate it again.

**Comment by njaffer** [comment]
done
