### ISSUE TITLE
Automated feed of valid depositors

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#20]
Depositor interactions with the repository are allowed when the user has an appropriate affiliation with the University of Michigan as defined by policy and represented in MCommunity/ORSP database

**Comment by grosscol** [comment]
Identity management problem.  Potentially mitigated by shibboleth integration with Devise & Apache should someone be ambitious enough to undertake this.

**Comment by njaffer** [comment]
This issue is tracked by #41
