### ISSUE TITLE
MVP: Support for multi-file objects, or "works"

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/umrdr#21]
An item deposited into the RDR must have at least one digital object attached to it, but may have more than one object (discrete files, zipped archives, etc.). Metadata applied to the item is by default applied to all constituent parts. Additional specific metadata may be applied to each constituent file. Files identified as data sets must have additional metadata to be defined.

**Comment by njaffer** [comment]
@grosscol: Sufia 7 supports it and is working so can this be closed?

**Comment by skorner** [comment]
Yeah, this MVP item was written around when PCDM was codified and still a long way from being incorporated into Sufia 7:) It seems fine to mark the need as met.
