### ISSUE TITLE
MVP: Flexible user- and group-based access controls

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/umrdr#23]
The RDR can pull user and group information from MCommunity for the purposes of authentication and authorization and proxy depositing.

**Comment by skorner** [comment]
This is more about using MCommunity (via ldap) to facilitate proxy assignment, ownership transfer, and other similar functions. Authentication will leverage cosign and is represented in #3.

**Comment by njaffer** [comment]
This MVP feature is tracked by #3
