### ISSUE TITLE
MVP: Fixity checking

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/umrdr#25]
Stores fixity information for deposited items and supports on-demand fixity verification.

**Comment by gordonleacock** [comment]
@colin, @skorner - I don't see any fixity checking UI control on the file_set page to enable on-demand fixity verification. Is that planned for the Feb. 29 release?

**Comment by skorner** [comment]
This was intended to be an MVP feature for repository admins and not users (I updated the MVP doc to clarify). On-demand fixity checking is provided by Fedora, so we are set. If the Sufia UI does eventually expose this to depositors, I expect we'll want to hide/disable it.

**Comment by grosscol** [comment]
+1 to not allowing users to demand hashes be recalculated for any objects.
