### ISSUE TITLE
MVP: Characterization of uploaded files

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/umrdr#27]
When a researcher uploads a new version of a previously-uploaded object, the previous metadata applied to that object is transferred. The researcher may update the metadata for the new version of the object.

**Comment by njaffer** [comment]
@skorner , @grosscol :  When the researcher uploads a new version, is it supposed to overwrite the previous one or is it uploaded as another work in the same collection? or another file in the same work?

**Comment by grosscol** [comment]
It's a different version of the same work.  By default, the current version is indexed and shown.  Pointing to previous versions for us becomes important as minting a DOI for a Work will point to that version of the work.

I have not checked the details of how the metadata for versions is maintained.  I have been under the impression, that the whole active-fedora object is versioned.

Works may or may not be in a collection.

**Comment by skorner** [comment]
Agreed on all points. Understanding precisely what's versioned and what functionality exists around versioning in Sufia is of interest to us, in particular as it relates to versioning transparency and access to prior versions.

**Comment by grosscol** [comment]
This ticket has wandered afield of it's original title and purpose.  Closing this as versioning is addressed elsewhere.
