### ISSUE TITLE
MVP: Forms for batch editing metadata

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/umrdr#28]
The metadata for any or all digital objects associated with an item, though a user selection, may be batch edited through a single interface.

**Comment by njaffer** [comment]
@skorner: is this for files in a work? or all the works in a collection? There is batch edit functionality in Sufia 7 for selecting all the works and batch editing them

**Comment by grosscol** [comment]
This is for works.  FileSets only have title descriptive metadata.

**Comment by skorner** [comment]
This MVP feature was based on Sufia 5/6 and pre-dates PCDM integration. It makes sense that batch metadata edit functionality is now at the works level.

**Comment by njaffer** [comment]
This issue can be closed as there is batch edit functionality for works  in Sufia 7 beta

**Comment by bnhowell** [comment]
What are the editable metadata properties in the batch edit page for works? Is there a batch edit function for files within a work? What are the editable metadata properties for files?
