### ISSUE TITLE
Standardize date formats (yyyy-mm-dd)

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#285]

**Comment by grosscol** [comment]
Backend validation can try to enforce the format of a given date string, however that's not advised.

This ticket has a UI component that @justcolin has an accessible approach for.  IIRC the plan is to providing separate fields for year, month, and day to be filled in.  

With separate year, month, and day fields, a DateTime object can be constructed.  The controller will have to construct the DateTime object. In this way, the model's validation should be that the attribute *is not a string* and is a DateTime object.

Related to #78, #99, #100.  DateTime will be required for coverage as coverage dates can include points around and before calendar reform.

It's an entertaining coincidence that this issue has been brought up again with such temporal proximity to Easter.

**Comment by njaffer** [comment]
Add 3 drop down boxes for year, month and day

**Comment by grosscol** [comment]
Talked to @justcolin.  In order to support ancient BCE dates, year field to be freetext that has a validation of digits only.

**Comment by njaffer** [comment]
server side validation or UI validation?

**Comment by grosscol** [comment]
For now, the UI, but both will have to be done.  I'll make another ticket for the controller and model implementation that needs to be done after the UI is satisfactory.

**Comment by jgmorse** [comment]
Does this platform have need to support date ranges?  We'll need to do that
on fulcrum.  (Fulcrum is what we're calling the Hydra publishing platform,
isn't that nice?)

On Thu, Apr 7, 2016 at 10:09 AM, Colin <notifications@github.com> wrote:

> For now, the UI, but both will have to be done. I'll make another ticket
> for the controller and model implementation that needs to be done after the
> UI is satisfactory.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mlibrary/umrdr/issues/285#issuecomment-206923711>
>



-- 
Jeremy Morse
Director of Publishing Technology
Michigan Publishing
734.615.5739

**Comment by grosscol** [comment]
@jgmorse That is beyond the scope of this ticket.  In short, the plan is to have a date range property for Works.  It's implementation is start date, end date.  Please use the slack channel or #78 for discussion about date ranges.

**Comment by njaffer** [comment]
@grosscol @justcolin: In my conversation with Colin F. the validation would be server side and not UI. Let talk more about this...

**Comment by njaffer** [comment]
Remove from UI (based on the discussion on Apr, 13, 2016)

**Comment by njaffer** [comment]
Closing the issue, the Date Created no longer exists in UI
