### ISSUE TITLE
Forms for batch editing metadata

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#29]
The metadata for any or all digital objects associated with an item, though a user selection, may be batch edited through a single interface.

**Comment by njaffer** [comment]
@grosscol: Can this be closed as it is a feature in Sufia 7

**Comment by grosscol** [comment]
Does batch editing apply to Works?  I was under the impression that the batch edits interface was for FileSets of a work.

**Comment by njaffer** [comment]
@grosscol: yeah when you select one or more works, the button for 'Edit Selected' and 'Delete Selected' appears
![screen shot 2016-02-09 at 1 34 53 pm](https://cloud.githubusercontent.com/assets/12487929/12926577/20bca436-cf32-11e5-836c-6f0de4234dad.png)
