### ISSUE TITLE
Use a namespace for redis.

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#301]
A sane namespacing scheme will allow multiple side by side deployments to use the same redis server.

**Comment by jgmorse** [comment]
Should other Hydra projects incorporate this same scheme?

**Comment by aelkiss** [comment]
Yes, absolutely. It's configurable in `config/initializers/curation_concerns.rb`; once we figure out what the scheme should be we can set it for heliotrope as well. This doesn't block deploying a staging instance of heliotrope locally; for now I just have two redis instances running on nectar.

**Comment by grosscol** [comment]
closed by #302
