### ISSUE TITLE
Sharing w/ groups and users/proxies

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#31]
Multiple people associated with an item may have shared ownership of the metadata and associated items. These groups might be managed within the RDR or via MCommunity groups.

**Comment by gordonleacock** [comment]
See also: issue #18.

**Comment by grosscol** [comment]
Permissions are granted on a per users basis.  See Abilities.  can: :edit

**Comment by njaffer** [comment]
This be closed once PR#1576 is merged in Sufia master
https://github.com/projecthydra/sufia/pull/1576

**Comment by njaffer** [comment]
projecthydra/sufia#1576 is merged in Sufia master

**Comment by grosscol** [comment]
For us this is still waiting on updating the dependencies which is not a given that it won't break our build.
