### ISSUE TITLE
Fix CSS 

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#311]
![screen shot 2016-04-07 at 9 31 41 am](https://cloud.githubusercontent.com/assets/12487929/14352663/94edb37e-fca3-11e5-84de-d60e78675e87.png)

![screen shot 2016-04-08 at 3 08 37 pm](https://cloud.githubusercontent.com/assets/12487929/14394749/d210bd98-fd9b-11e5-9066-a2aed3328a8c.png)

**Comment by grosscol** [comment]
closed by #328
