### ISSUE TITLE
Create a static page for Terms of Use

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#320]
The Terms of Use is part of Policy document. @amyneeser mentioned that when a user agrees to terms upon deposit, the deposit agreement is linked to the entire policy document, rather it should be linked to only Terms of Use.

To Do: Create a new page for Terms of Use from Policy Document and link it to Deposit Agreement on New Works page

**Comment by grosscol** [comment]
Or just link to the terms of use section of the policy document.

**Comment by amyneeser** [comment]
Research is requesting Terms of Use be on a separate page so the user doesn't think they have to read / are agreeing to the entire policy document. There can be a link to the full policy document under the Terms of Use.

**Comment by grosscol** [comment]
They don't have to agree to the Terms of Use?

**Comment by amyneeser** [comment]
The Terms of Use is the part General Council wants them to read and agree to upon deposit.

**Comment by justcolin** [comment]
@amyneeser: Do you want me to just copy the Terms of Use section of that one page into a new page or cut it out and create a new page with it?

**Comment by justcolin** [comment]
@amyneeser said to copy it.
