### ISSUE TITLE
Create date and date range fields in the UI

### ISSUE THREAD

**Issue by justcolin** [mlibrary/umrdr#324]
Create a date and date range set of fields for forms. When we talked with @amyneeser the best course of action sounded like a text or number field for the year, a drop down for the months, and a drop down for the date. Date ranges will be two sets of those three fields.

If an `<input type="number">` is used you can set `min="0"`. Whichever type is used, we may want to add `inputmode="number"` to the year field.

**Comment by jonearley** [comment]
Potential solution: https://github.com/mlibrary/umrdr/pull/327

**Comment by njaffer** [comment]
[Duplicate Issue]. Closing this issue, the conversation is tracked on #100
