### ISSUE TITLE
"Deposit Your Work" disappeared from the home page

### ISSUE THREAD

**Issue by justcolin** [mlibrary/umrdr#329]
Let's go on a magical journey to get it back.

**Comment by jonearley** [comment]
@njaffer, @grosscol 

There is a conditional on the user if they can view the button. Relevant line: https://github.com/mlibrary/umrdr/blob/0646590a26a634c2dc03e06279fa0c98838956f3/app/views/sufia/homepage/_home_header.html.erb#L8

Is this conditional necessary? Should I be able to view, but permissions are having an issue?

**Comment by njaffer** [comment]
Good find @jonearley. I will look at the code to see why it is not true

**Comment by njaffer** [comment]
@respinos: Looking at this line: https://github.com/mlibrary/umrdr/blob/0646590a26a634c2dc03e06279fa0c98838956f3/app/views/sufia/homepage/_home_header.html.erb#L8

Wondering why do we need that? When I am not logged in, I can still access the Deposit Work from the nav bar, so why are we checking for abilities here?

**Comment by njaffer** [comment]
@jonearley: Thanks for pointing that out, it should be looking for can? on GenericWork and not FileSet
