### ISSUE TITLE
Background jobs

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#33]
Ability to offload virus checking and other potentially intensive or time consuming jobs.

**Comment by gordonleacock** [comment]
@grosscol, @skorner, @aelkiss - Am I right in assuming that this feature is implemented via a redis-server a la sufia. Is virus checking currently implemented?

**Comment by skorner** [comment]
Yes, there will be a Redis instance to support Sufia's background/offload capabilities. @aelkiss noted that virus checking is now in [hydra-works](https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/models/concerns/file_set/virus_check.rb), so it will happen synchronously on deposit. We'll make sure clamav is available in production (it's already there in dev). [Here](url) are instructions on how to enable its use.
