### ISSUE TITLE
Integrate Google Analytics

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#345]
fix analytics in user profile

**Comment by grosscol** [comment]
After enabling analytics, the analytics buttons on both FileSet and Work do not use relative_url_root.  This might be an upstream issue as well.

**Comment by amyneeser** [comment]
What is the status on this?

**Comment by grosscol** [comment]
Current work is on the feature/analytics branch.
Needs to be reconciled with the sufia7 update #391
