### ISSUE TITLE
Integration w/ cloud storage providers

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#35]
Researchers must be able to trigger the direct ingest of their materials from Box and Dropbox accounts to which they have credentials. This is one way (from cloud to RDR) for the alpha. Later versions may allow "pushing" of digital objects from the RDR to a user's Box/Dropbox account.

**Comment by grosscol** [comment]
Browse everywhere needs to be enabled.  API keys still need to be obtained using the core services credentials.

**Comment by gordonleacock** [comment]
From Slack:
@aelkiss: I’ve been developing on my desktop so @grosscol pulled BE back. Here is where BE stands:
— There is a projecthydra BE repo at https://github.com/projecthydra/browse-everything/wiki/Configuring-browse-everything with config instructions there.
— Sufia is already largely set up to use BE. For example, the engine mount is already in routes.rb.
— config/browse_everything_providers.yml needs to be created and filled it for box and dropbox plus an upload limit.
— I was assuming that we will using BE from javascript, that will require some links/buttons are added to upload files.
 
GitHub
projecthydra/browse-everything
browse-everything - Rails engine providing access to files in cloud storage

Next steps are: 1) Generate dev credentials if needed. 2) Add javascript as described at: https://github.com/projecthydra/browse-everything readme. 3) Test.
 
GitHub
projecthydra/browse-everything
browse-everything - Rails engine providing access to files in cloud storage

**Comment by aelkiss** [comment]
Thanks. Here's my current plan:

- Register new API keys for umrdr-test.quod.lib.umich.edu
- Configure firewall & apache to allow access to necessary paths for callbacks
- Test adding JS as in the path you listed

**Comment by aelkiss** [comment]
Working on this on the [browse-everything branch ](https://github.com/mlibrary/umrdr/tree/browse-everything). Current status:

- OAuth2 integration with Google Drive and Box is working; you can connect and list files
- Actually attaching files via Browse Everything to a Fileset does not yet work

The OAuth2 callback does NOT require access from Google or Box to your local machine -- you may be able to get it working with an /etc/hosts alias -- but it is probably easier to continue developing this via umrdr-testing.quod.lib.umich.edu. Let me know if you want the API keys that work with that.

**Comment by njaffer** [comment]
Tested with Google Drive
