### ISSUE TITLE
MVP: Google Scholar-specific metadata embedding

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#36]
Ensure that the schema.org Scholarly Article (http://schema.org/ScholarlyArticle) Web Observatory (http://www.w3.org/wiki/WebSchemas/WebObsSchema), or similar metadata microformat is used to characterize each item.

**Comment by njaffer** [comment]
@skorner , @grosscol: Should we close this issue or do we need this?

**Comment by skorner** [comment]
The understanding of the investigation team last year was that Sufia provided this out of the box. If it still does and requires no effort to utilize, then go ahead and close this issue. If Sufia does not provide this functionality or it requires effort to implement it, then I'm sure it can wait (DUCTF came to the same conclusion when evaluating the MVP list back in October).

**Comment by amyneeser** [comment]
Nabeela is going to ask Jim O. if his DBD deposit is showing up on his Google Scholar page.

**Comment by amyneeser** [comment]
Jim O. confirmed that this is not working. We need to revisit how to get this working.
