### ISSUE TITLE
Fix date-coverage UI

### ISSUE THREAD

**Issue by jonearley** [mlibrary/umrdr#360]

**Comment by jonearley** [comment]
I understand the date-coverage UI has some focus issues from my last PR https://github.com/mlibrary/umrdr/pull/327. I'll work to fix that.

Are there any other issues I should address? @njaffer @grosscol

**Comment by jonearley** [comment]
Turns out there is no focus issue. The version in master is OK after reviewing it with @justcolin.

**Comment by grosscol** [comment]
I was getting the focus issue where I fill in a start date, tab over to the button for adding an end date.  Use that, and the field focus is back at the start date again.  I was expecting the selected field to be at the year of the end date.

**Comment by jonearley** [comment]
Alright, good catch. I'll make that change this week.
