### ISSUE TITLE
Depositor being truncated at the dot

### ISSUE THREAD

**Issue by cmkpowell** [mlibrary/umrdr#367]
If I am looking at a work and click on the depositor email address, I am told they are not found. The error message indicates that .edu is being left off. 

![aneesernotexist](https://cloud.githubusercontent.com/assets/16540397/15615840/82a0bd8c-240e-11e6-963b-223779c84235.png)

**Comment by grosscol** [comment]
The links for the users profiles should actually be resolving to `uniqname@umich-dot-edu`.  There may have been a helper for this that was circumvented.

**Comment by njaffer** [comment]
This is an old issue, and not relevant with the current UI
