### ISSUE TITLE
Blank / Invisible text for search group drop down.

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#368]
Selecting the scope for search should display All, MyWorks, MyCollections for a logged in user.  The drop down is blank.

![dbd_invisibletextdropdown](https://cloud.githubusercontent.com/assets/1520508/15712247/a1ab3106-27df-11e6-9a78-e5670e473cc2.png)

**Comment by njaffer** [comment]
@justcolin , @jonearley: It is css issue, the items "All", "My Works" and "My Collections" is there but the font color is white.

**Comment by justcolin** [comment]
Fix will be in place when `sufia7_update` is pulled into `master`.
