### ISSUE TITLE
Add Data Management Plan boilerplate language to help pages

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#370]
Add [Data Management Plan boilerplate language](https://docs.google.com/document/d/1t5VxQwI0BFYfFM6UcH5UaXljf7iM2xa3xqhiT86xsUc/edit) as a subpage titled "Data Management Plan (DMP) boilerplate language" to [Support for Depositors page](https://deepblue.lib.umich.edu/data/support-for-depositors).

**Comment by grosscol** [comment]
Add the text quoted below as a new static page.  Link to the page prior to "Planning" (see screenshot in prior commment) using "Text for DMPs".

> The data generated through this project will be deposited into Deep Blue Data, the University of Michigan's institutional data repository. Deep Blue Data has been developed by the U-M Library to assist researchers in complying with grant-funding agency requirements. 
> 
> Content in Deep Blue Data is stored on networked storage operated by U-M Information and Technology Services (ITS) in campus data centers. ITS provides the Library with a single active instance of the content on spinning disk and a nightly replica of the content to an alternate campus datacenter for disaster recovery purposes only. Tape backups with 6-month retention are conducted nightly using the campus-operated tape backup service and are also replicated to a remote site nightly. More details about the storage service are available at http://services.it.umich.edu/mistorage and about the tape backup service at http://services.it.umich.edu/mibackup.
> 
> During deposit, researchers include documentation for the data and assign metadata to the data to facilitate its discovery and use. The metadata can be harvested by search engines such as Google Scholar. Data sets are assigned a Digital Object Identifier (DOI) as a persistent identifier for the data, enabling the data to be cited in publications. Researchers select a Creative Commons license as a part of the deposit process to describe the conditions under which others may use the data. Deposited data will be accessible through the Deep Blue Data for at least 10 years, after which it will be appraised for continued preservation by University Library personnel.

**Comment by amyneeser** [comment]
Intro text: The text below can be inserted into your data management plan to indicate your use of Deep Blue Data as a means to share and preserve your data.

**Comment by njaffer** [comment]
"Text for DMPs" would go below "Support for Depositors"
