### ISSUE TITLE
clip description field when displayed in search results 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#377]
Put a maximum number of characters for the description field on search result page. Could we have a "show more" button or something else? 
![screen shot 2016-06-02 at 12 15 19 pm](https://cloud.githubusercontent.com/assets/3106478/15752419/fc232756-28bb-11e6-9e02-45863cebc0e8.png)

**Comment by grosscol** [comment]
By what heuristic would you like this shortened in the display?  Is 500 characters followed by an ellipse acceptable?

**Comment by amyneeser** [comment]
That sounds great!

Amy

**Comment by blancoj** [comment]
Colin is it OK if I give this a try?

**Comment by amyneeser** [comment]
This is done.
