### ISSUE TITLE
'My Collections' page header mismatch

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#378]
![screen shot 2016-06-06 at 8 51 07 am](https://cloud.githubusercontent.com/assets/12487929/15822483/0314a520-2bc4-11e6-9823-2fdb841a2e13.png)

**Comment by njaffer** [comment]
@grosscol:Both My Works and My Collections headers come from this file: https://github.com/mlibrary/umrdr/blob/master/app/views/my/_index_partials/_default_group.html.erb

Do we want to display Open Access for both Works and Collections?

**Comment by grosscol** [comment]
For the time being, yes.  The table header is missing "Visibility" between "Uploaded" and "Action"

Similar to #379
