### ISSUE TITLE
'View Work' Files widget header mismatch 

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#379]
![screen shot 2016-06-06 at 8 56 31 am](https://cloud.githubusercontent.com/assets/12487929/15822588/af82931c-2bc4-11e6-8dd8-2de566ad3f31.png)

**Comment by grosscol** [comment]
The header needs to be updated in include visibility.

**Comment by amyneeser** [comment]
Let's use "Access" for the header.
