### ISSUE TITLE
In place data model migration

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#384]
related to Sufia 7 update PR

**Comment by grosscol** [comment]
Data currently being entered into production is using a model of FileSet and File that is no longer compatible with the Sufia 7.0 infrastructure. At least the characterization metadata will have to be migrated from the FileSets.

**Comment by njaffer** [comment]
Worked with @grosscol to see how data differs in Sufia7_update branch. Here is what we found: After reindexing data in solr, the old data is restricted and cannot be viewed. After changing the edit_groups and read_groups on both fileset and work, the work was viewable.
