### ISSUE TITLE
Add browse functionality

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#388]
We need a way for users to be able to see what is in the repository. Probably a browse button. Browse options could be the current search facets: discipline, creator, keyword, etc.

**Comment by grosscol** [comment]
Implement via button that links to blank search.  Directly under 'Deposit Your Work' button on dashboard.  Same style.  Using text "Browse Datasets"

**Comment by njaffer** [comment]
@justcolin: Can you create a button similar to `Deposit Your Work` with the text `Browse Datasets`

**Comment by justcolin** [comment]
@njaffer: Where should this button go?

**Comment by njaffer** [comment]
@justcolin: After this line: https://github.com/mlibrary/umrdr/blob/sufia7_update/app/views/sufia/homepage/_home_header.html.erb#L10
something like this would be added:
 <%= link_to "<i class=\"glyphicon glyphicon-upload\"></i> #{t('sufia.browse_button')}".html_safe, main_app.search_catalog_path, class: "btn btn-primary", id: "contribute_link" %>

**Comment by justcolin** [comment]
@grosscol: Best way to programmatically get a link to a blank search?

**Comment by njaffer** [comment]
@justcolin, @grosscol : Is `main_app.search_catalog_path` not the best way?
