### ISSUE TITLE
Add metadata box for Deep Blue Document Handle

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#389]
This is the first step in linking Deep Blue to Deep Blue Data.

**Comment by njaffer** [comment]
related to #362

**Comment by amyneeser** [comment]
Title: Citation to Related Work(s)
Help text: Related publications that reference/use/describe the data. Paste the full citation or just include a URL. Ex. DOI:240857083.352.523.4

**Comment by njaffer** [comment]
With the long title 'Citation to Related Work(s)', the button text cuts off
![screen shot 2016-07-25 at 3 45 18 pm](https://cloud.githubusercontent.com/assets/12487929/17114891/ea6b0906-527e-11e6-9ca3-3659796cf06e.png)

@grosscol , @justcolin: Any ideas?

**Comment by justcolin** [comment]
I'll fix it

**Comment by njaffer** [comment]
Thank you @justcolin!

**Comment by justcolin** [comment]
@njaffer: what's the URL for the page that this field appears on?

**Comment by njaffer** [comment]
It is on new work and edit work page

**Comment by amyneeser** [comment]
Update: we need this for works AND collections.

**Comment by njaffer** [comment]
@amyneeser: I will create a separate ticket for adding it to collection. This ticket is essentially done once @justcolin updates the css for the button text.

**Comment by amyneeser** [comment]
Change text on button to: add citation
