### ISSUE TITLE
Disable mint DOI unless file is attached

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#390]
We want to disallow users from minting a DOI on a blank deposit.

**Comment by grosscol** [comment]
Replace mint doi button with help text stating that a file is required in order to mint a doi.  @amyneeser to determine the exact text to be added to localization.

related to https://github.com/mlibrary/umrdr/issues/52

**Comment by amyneeser** [comment]
Use language: "Upload file to generate DOI."
