### ISSUE TITLE
unauthorized error message on deposit page

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#393]
Authorized users are getting this message when they click on "deposit your work."

![screen shot 2016-07-21 at 2 09 37 pm](https://cloud.githubusercontent.com/assets/3106478/17033586/dc6f0b16-4f4c-11e6-84e7-9ed315914416.png)

**Comment by grosscol** [comment]
Unable to replicate this error today.  @amyneeser is this still a problem for you?

**Comment by amyneeser** [comment]
Nope, it's no longer there. Thanks!

**Comment by amyneeser** [comment]
Nabeela found it again.

**Comment by grosscol** [comment]
I see.  You can still deposit a work, and the message is incongruous with the behavior of the page.
