### ISSUE TITLE
remove audit status and characterization from file view page

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#401]
<img width="601" alt="screen shot 2016-07-25 at 2 55 31 pm" src="https://cloud.githubusercontent.com/assets/3106478/17113264/e6d14c12-5277-11e6-8eb5-208d4a900ca0.png">

**Comment by njaffer** [comment]
done - can be closed after merging sufia7_update branch with master
![screen shot 2016-07-26 at 1 24 32 pm](https://cloud.githubusercontent.com/assets/12487929/17148253/657be628-5334-11e6-99b5-a88b502a910e.png)
