### ISSUE TITLE
Add template import yml for ingest script.

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#405]
The importer tasks requires an input yaml file that contains the metadata, filenames, and structure of the works/collections to be imported.  Add a template file for use by research data services when preparing a batch of files for import.

Depends on #392

**Comment by amyneeser** [comment]
Let's investigate using .csv

**Comment by njaffer** [comment]
@amyneeser closing this ticket, we have the .csv and .yml for the ingest
