### ISSUE TITLE
Set config.display_media_link to false in such a way CurationConcerns can access it.

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#408]
PR #352 overrode two view partials.  The `media_display/_default.html.erb` is provided by Sufia, and `media_display/_image.html.erb` provided by CurationConcerns.

The override of the `media_display/_default` partial changes the behavior back to the CC implementation.
The override of the `media_display/_image` overrides nearly the exact same code as CC was already providing.  The issue with the CC partial, is that the configuration to display the media download link does not appear to be directly accessible from a Sufia based app as the Curation Concerns initializer is no longer a part of Sufia's install generator.

Find a way to set `display_media_link` to `false` in the config in such a way that the partial provided by Curation Concerns will pick up on it and not render a link to download the media for FileSets.
`app/views/curation_concerns/file_sets/media_display/_image.html.erb`

**Comment by amyneeser** [comment]
Related to large icon size and download PDF issue.
