### ISSUE TITLE
Remove single use links

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#44]
Superfluous functionality that should be removed, but isn't breaking the desired application functionality currently.

**Comment by jgmorse** [comment]
This is a good example of where needs diverge among our Hydra apps.  MPub could make good use of this feature.

**Comment by grosscol** [comment]
It's in stock Sufia, so it shouldn't be an issue for MPub.

**Comment by grosscol** [comment]
Overriding named routes cannot be done by simply declaring the same one and letting the last declared win.  Need to either sort out how to override the routes inherited from CurationConcerns::Engine OR override and no-op the SingleUseLinkController

**Comment by grosscol** [comment]
in short `data/single_use_link/generate_show/<id>` should not be available nor routable.

**Comment by njaffer** [comment]
@grosscol , @bnhowell , @justcolin : Are we removing the access to single use link from view collection screen also?
![screen shot 2016-02-15 at 11 11 05 am](https://cloud.githubusercontent.com/assets/12487929/13053936/1486d43c-d3d5-11e5-93e6-71b75da6b93f.png)

**Comment by grosscol** [comment]
@njaffer @justcolin Yes.  The Single-Use Link to Work needs to be removed from the UI as well.

Those overrides are overrding the following partials:
`app/views/my/_action_menu.html.erb`
`app/views/collections/_show_document_list_menu.html.erb`
`app/views/collections/_action_menu.html.erb`

It's a relatively easy deletion, so it could be added to a solution for the routing issues.  It will get merged with @justcolin's branch of work.

**Comment by justcolin** [comment]
I don't know what it does, so I don't have an opinion.

**Comment by justcolin** [comment]
I will still need to delete it from the template since I am pretty sure we are already overwriting that one in the app.

**Comment by njaffer** [comment]
Solution: Delete L4 from view file(app/views/single_use_links/new_show.html.erb) and change the text on L3 to "Sorry, Single Use Link  Access is not available". Here is reference to this view file on Sufia master: https://github.com/projecthydra/sufia/blob/fa0190067b76f825d2e017ceb1dca7fb95cbe250/app/views/single_use_links/new_show.html.erb

**Comment by justcolin** [comment]
Do we need the text saying the link is unavailable? As far as I know —and please correct me if I am wrong—there is no expectation for it to be there, so adding a note about its absence just clutters things up.

**Comment by njaffer** [comment]
The only reason to put some text is that in case the user types in the single use link address manually, there should be some message to let them know that it is not available for this repo.

**Comment by justcolin** [comment]
@grosscol: is that a real concern?

**Comment by grosscol** [comment]
@justcolin Yeah.  Getting rid of it in the UI is probably going to cover us.  Manually typing in the route or getting there from a link we missed would generate ActiveFedora objects.  @njaffer covered the issue of generating objects in #66

**Comment by njaffer** [comment]
closed with #66
