### ISSUE TITLE
My profile shows all works under my created works 

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#442]
<img width="889" alt="screen shot 2016-09-19 at 10 19 57 am" src="https://cloud.githubusercontent.com/assets/12487929/18635778/2f98a5aa-7e54-11e6-9b41-23637e73ab35.png">

**Comment by njaffer** [comment]
@amyneeser, @grosscol: Debugging this issue might take longer. Should we remove the option of 'Works Created' from this screen?

**Comment by amyneeser** [comment]
@njaffer That seems like a reasonable temporary fix to me.

**Comment by njaffer** [comment]
This is an issue upstream: https://github.com/projecthydra/sufia/issues/2708

**Comment by grosscol** [comment]
Overriding another partial as a band aid will increase the amount of technical debt we carry into future versions.  I'm inclined to wait for the upstream fix.

**Comment by amyneeser** [comment]
We do not need this feature because it is duplicative with "my works". Please remove it.

**Comment by billdueber** [comment]
Close by #453
