### ISSUE TITLE
User can upload files without accepting the deposit agreement

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#445]
<img width="1110" alt="screen shot 2016-09-19 at 10 50 00 am" src="https://cloud.githubusercontent.com/assets/12487929/18636483/0154f3da-7e57-11e6-9f69-3e754c4608de.png">

**Comment by billdueber** [comment]
Look for identical structure in vanilla sufia to see where it's doing; should be javascript attached to the submit button? How is client-side validation done in general in this code stack?
