### ISSUE TITLE
Confusing behavior when removing a proxy

### ISSUE THREAD

**Issue by cmkpowell** [mlibrary/umrdr#447]
I clicked on the trashcan and it showed a blank notification screen with a Delete All button.  I didn’t know what to do so I hit the back button and saw the Proxy still there.  When I clicked on the trashcan again I got an error saying 

The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.
**But when I clicked on the Current Proxies X, that just disappeared.**

If I reload the page the User Notification clears.  I probably shouldn’t have used the back button, but that is what people do when they get confused.  GDoc has images.

**Comment by botimer** [comment]
I was planning to split this issue into validation and more detail of the desired behavior... But with a further look, this seems to be a pretty direct UI bug. We can at least verify it in this sprint.

**Comment by njaffer** [comment]
@blancoj and I looked at this issue, and there is no notification when a proxy is removed. The solution would be to put a user notification when the proxy is removed
