### ISSUE TITLE
Unclear which file will be downloaded

### ISSUE THREAD

**Issue by cmkpowell** [mlibrary/umrdr#452]
At https://staging.deepblue.lib.umich.edu/data/concern/generic_works/hq37vn56b there are three linked PDFs.  The "Download the full-sized PDF" link by the large document icon displays/downloads the middle of the three linked files.  It doesn't display a name, so it's not clear which file you will be getting.

Additionally, is it necessary for the document icon to be so large?

**Comment by amyneeser** [comment]
I'd prefer a smaller icon size.

**Comment by grosscol** [comment]
@amyneeser Please, make an icon size issue.

**Comment by amyneeser** [comment]
Remove link "download the full size PDF".

**Comment by billdueber** [comment]
Link eliminated by #473
