### ISSUE TITLE
Logout not returning to application in logged out state

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#454]
At first glance, was thought to not be properly redirecting (issue #443).  

Log out does not appear to be functioning as expected.  When clicks logout, the application instructs the browser to delete the session cookie and redirects the user to cosign logout.  After logging out via cosign, the user is redirected back to the application. 

At this point, it appears that the session is still active.  It is possible that the session cookie is not actually removed by the browser.  Perhaps different parameters to `cookies.delete` are required.  Possibly `host:`.

https://github.com/mlibrary/umrdr/blob/master/app/controllers/sessions_controller.rb#L4-L5

**Comment by botimer** [comment]
The Rails session is being terminated, but the Cosign cookie is not being purged. `cookies.delete` requires `domain:` to be specified. That will take care of the main issue here.

However, a slightly better behavior is to only terminate sessions on logout confirmation. This allows for the "cancel" behavior supported by Cosign to work as expected. It can be accomplished by passing to Cosign a "return URL" that purges cookies and then passes on to the front page. I have used a `logout_now` route for this elsewhere.

FWIW, this URL is not linked or really visible anywhere (outside of logs or the redirect chain), but it does no harm if someone goes to it directly -- it just "logs them out now". (Also, this naming comes from earlier editions of Weblogin, where the buttons were labeled "Go back" and "Logout now".)

I'll have a pull request soon.

**Comment by botimer** [comment]
This StackOverflow question was helpful in tracking down the exact host-only behavior:

http://stackoverflow.com/questions/16301690/should-a-cookie-with-the-host-only-flag-replace-a-cookie-without-it
