### ISSUE TITLE
File action drop-down is visually clipped by the "Files" panel

### ISSUE THREAD

**Issue by botimer** [mlibrary/umrdr#459]
As seen on https://deepblue.lib.umich.edu/data/concern/generic_works/n870zq819 using Chrome 53, OSX 10.11.6.

The drop-down is occluded by the border of the panel:

![action-clipping](https://cloud.githubusercontent.com/assets/159019/18923095/189e7e5c-8579-11e6-83e8-2f7e10b964f6.png)

**Comment by amyneeser** [comment]
Remove drop down list. Add link / button that says "more details" and link to page that includes: 

edit
versions
delete 
download

**Comment by njaffer** [comment]
@bnhowell: Can you please review this

**Comment by blancoj** [comment]
@amyneeser I asked @bnhowell  about this issue, he recommended a text link to "View Details"  Let me know.  Also presently the drop down has a link to versioning.  @njaffer tells me we're not doing anything with this, and it is not present in the file metadata page, so I'm not going to bother putting it in the file metadata page.  Make sense?

**Comment by amyneeser** [comment]
A text link sounds fine to me too. Thanks for checking with @bnhowell
