### ISSUE TITLE
create message on work that indicates data is embargoed

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#462]
Background: This user submitted data that is associated with his dissertation and needs it to be embargoed until September 2017. Because we do not yet have this functionality in place, I downloaded his data and asked him to delete the files but leave the works visible. 

Can we put a notification on his works that indicate the data is embargoed until September 2017? 

It is for the following works: 
https://deepblue.lib.umich.edu/data/concern/generic_works/nc580m674
https://deepblue.lib.umich.edu/data/concern/generic_works/vh53wv75j
https://deepblue.lib.umich.edu/data/concern/generic_works/3484zh00p
https://deepblue.lib.umich.edu/data/concern/generic_works/x920fw90j
https://deepblue.lib.umich.edu/data/concern/generic_works/w9505053x
https://deepblue.lib.umich.edu/data/concern/generic_works/jq085j99x
https://deepblue.lib.umich.edu/data/concern/generic_works/s1784k77h
https://deepblue.lib.umich.edu/data/concern/generic_works/4b29b6007

**Comment by amyneeser** [comment]
Can we just add the embargo information to the title?

**Comment by amyneeser** [comment]
Add the following text at the end of each title: (embargoed until September 2017)

**Comment by njaffer** [comment]
Done
