### ISSUE TITLE
Order file names that are attached to a work 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#466]
## Background or Context
When files are uploaded to a work, there is no ordering for how they are displayed. 

## Desired Behavior/Capability
We have gotten a request from a researcher to order files attached to a work alphabetically. Can we investigate the level of difficulty for ordering files?

**Comment by njaffer** [comment]
The files are in the order of upload. When uploaded via rake test, they can be deposited in alphabetical order. The latest CC has UI File Manager. When it will be merged with Sufia, we will have that functionality as well.
