### ISSUE TITLE
Enable route to database login in development environment

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#48]
After enabling cosign authentication, the standard method of authentication should remain accessible for development environments.

Use `Rails.env.development?` in routes to set up a route that either resolves to the database login page or simply gives auth.

Related to #3

**Comment by aelkiss** [comment]
Use cases:

- development on local machine (cosign is managed by apache, so it won't work when using e.g. http://localhost:3000)

- convenience for logging in as multiple users for testing proxy deposit

**Comment by grosscol** [comment]
Addressed by #83.  Uses ENV['USER'] by default in the faked HTTP_X_REMOTE_USER header.
