### ISSUE TITLE
When user clicks on work, display contact information for creator. 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#481]
## Background or Context
Possible solution: link to user profile, which must then contain e-mail address.

**Comment by njaffer** [comment]
display depositor email address

**Comment by blancoj** [comment]
@amyneeser is this what you want?:

<img width="959" alt="screen shot 2017-01-09 at 12 35 41 pm" src="https://cloud.githubusercontent.com/assets/11095558/21776412/47d6575e-d668-11e6-92ff-1c89e1bf752f.png">

**Comment by njaffer** [comment]
@blancoj: When you click on the email address for the depositor, do you see user profile page?

**Comment by blancoj** [comment]
@amyneeser  I just talked to @bnhowell about the Depositor metadata, and his recommendation is to have it just be text so user can cp/pt the email.  I'm fine with any decision.  Just wanted to pass that along. Let me know.
