### ISSUE TITLE
Disable edit and delete this work if DOI is created

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#482]
## Background or Context

If DOI is minted, disable: 
edit this work 
delete this work

**Comment by njaffer** [comment]
@amyneeser: Are we disabling or  hiding the buttons? @blancoj has put in PR that will hide the buttons if DOI is minted. Do you have some help text to display instead of the buttons?

**Comment by amyneeser** [comment]
Do not hide the DOI. Grey out the button as @blancoj suggested. 

Next to the button, add text: to mint a DOI, first upload files.

**Comment by njaffer** [comment]
@amyneeser:  @botimer commented on the PR, regarding the word 'mint' versus 'assign'.  Should we change the help message to "Once a DOI is assigned, you cannot edit or delete your work. Contact us [link to: https://deepblue.lib.umich.edu/data/contact] with questions.
