### ISSUE TITLE
DOI domains for production and staging are incorrect.

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#486]
## Background or Context
The current method of reading the EZID url prefix from the environment settings is incompatible with the deployment and application startup processes.  In short, the environment variable is not set in production.

Since the environment variable for the doi prefix is not set, the application uses the default url prefix.  That prefix is incorrect for production.  This results in broken links for the DOIs:

> Dear EZID user "umich",
> 
> You are receiving this message because the EZID link checker has
> discovered that 14 of your identifiers have broken target URLs
> (also referred to as object locations).  A broken target URL is
> one that has failed to load for at least two weeks.  Attached to
> this message is a ZIP-compressed, Excel-compatible CSV file
> listing the identifiers in question, their target URLs, and
> other pertinent information.
> 
> There are many reasons a target URL may be broken.  The
> identified object may have moved, in which case the identifier
> needs to be updated.  Or there may be a problem with the server
> hosting the URL.  If an object is no longer available, the
> identifier's status can and should be set to "unavailable" using
> EZID's UI or API.
> 
> Best,
> EZID Team

The urls that were broken as of Nov 14 were updated manually by @skorner.

## Desired Behavior/Capability
Expected the DOI domain for production to be deepblue.lib.umich.edu

## Existing Behavior/Capbility
The observed DOI doi are prefixed with umrdr.umich.edu

## Steps to reproduce or demonstrate
1. Mint a doi for a work using the ezid testing credentials.
2. Observe the result of resolving the doi at dx.doi.org

**Comment by skorner** [comment]
FYI, the new DOIs being minted since the late December release have the proper domain. This issue was most likely resolved by the changes made to `config/application.rb` and `config/settings/production.yml` as part of #454.

**Comment by njaffer** [comment]
@skorner: awesome. Thanks!
