### ISSUE TITLE
Explore Google crawling for Deep Blue Data

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#488]
## Background or Context
Do we need to do anything extra to get Google to crawl the Deep Blue Data metadata?

**Comment by blancoj** [comment]
Google is crawling our site.  You can see that if you search for one of our titles in google, you'll find it.  Here is an example:
https://www.google.com/#q=ENVIREM:+ENVIronmental+Rasters+for+Ecological+Modeling

I tried to find out how often google crawls our site, but there is no definitive answer to that question.  Here is some documentation on that:

https://support.google.com/webmasters/answer/70897?hl=en&ref_topic=4558960#1

We are not using sitemaps presently.
