### ISSUE TITLE
Second validation prior to indexing

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#5]
Currently the validation is done prior to `save!` which will persist and index the object.
Change validation to require title before persisting to fedora, but do not index into solr until a minimum set of metadata has been entered.

@grosscol said:
>I think I'm going to write the validator to only index works with at least a minimum set of metadata.
>Since we're not able to index the contents of the files. The only thing we have to go on its the metadata and abstract or readme.
>So it's probably not to big of a deal to mark non validated works as draft

**Comment by grosscol** [comment]
Need a list of minimum metadata for a work prior to indexing.
Proposed:
* title
* creator (with default to depositor)
* description
* date created (with default to current date)

**Comment by amyneeser** [comment]
Leave date created required. Do not default to current date.

**Comment by grosscol** [comment]
Per @bnhowell just changing all four fields to required for saving.  This simplifies the application logic and is a good plan.

**Comment by grosscol** [comment]
Should have been closed by #57, but requires an upstream bug fix to Curation Concerns or modification of our GenericWorksControllerBehavior to call `build_form` prior to `render: 'new'`

**Comment by njaffer** [comment]
@grosscol: Can we close this one. It is related to PR #63 or should we move it to Milestone 2.0?
