### ISSUE TITLE
Move "I have read and agree..." checkbox on deposit work page

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#514]
## Background or Context

Move "I have read and agree..." box and text after the work description box and files box. 

<img width="822" alt="screen shot 2016-12-05 at 9 58 48 am" src="https://cloud.githubusercontent.com/assets/3106478/20889640/ac0fb056-bad1-11e6-8fa0-65ac13709e4b.png">

**Comment by blancoj** [comment]
After talking this over with @amyneeser and ben for now we won't be moving the checkbox.
