### ISSUE TITLE
Download file on work page when user clicks on file name 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#517]
## Background or Context
On work page, clicking on the filename takes user to page with information about the file rather than directly downloading it. 

## Desired Behavior/Capability
When user clicks on filename on work page, download the file directly.

**Comment by blancoj** [comment]
@aelkiss what do you think of this?  When you click c.txt it behaves as the if you select Download from the pick list.  I added View Metadata to the pick list, and that sends you to the file metadata page.  Will this work?

<img width="1872" alt="screen shot 2016-12-07 at 9 45 20 am" src="https://cloud.githubusercontent.com/assets/11095558/20972280/61791d1a-bc62-11e6-96ae-ea34d745b621.png">
