### ISSUE TITLE
Document File Ingest Workflow

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#519]
Message from Amy:
if / when files are scanned for viruses
if / when formats are verified 
if / when the checksum is run
what system generated metadata is there (for files themselves and works)
how can we access metadata that is not displayed   
how does it arrive to and live in Fedora
is there a unique identifier (permanent?) 
can we create unique id for files? (not DOI since it is optional)

**Comment by amyneeser** [comment]
Also, what is the mechanism to track changes made to content (files, metadata, etc.) in Deep Blue Data?

**Comment by njaffer** [comment]
https://docs.google.com/document/d/1qanrPSEwJ_OhaHbcb8taPWNQaf4Y4oJL51TnCjXlZto/edit
