### ISSUE TITLE
Add batch download capability

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#520]
## Background or Context 

Add a way to batch download multiple files at once rather than having to download them individually.

**Comment by amyneeser** [comment]
Batch download all files as a zip.

**Comment by njaffer** [comment]
Question: Show the button 'Download All Files' even when there is only one file? Maybe question for Ben

**Comment by blancoj** [comment]
@amyneeser how does this look:

<img width="1658" alt="screen shot 2017-01-19 at 4 07 43 pm" src="https://cloud.githubusercontent.com/assets/11095558/22125430/a61d224c-de61-11e6-8537-d3da45ecf49f.png">

**Comment by amyneeser** [comment]
What would be good wording for this, @bnhowell? If they click "download zip file" they can get all the files at once. How about something like: 

Download zip file to download all the files in this work.

**Comment by jakecarls** [comment]
I would just have the text for the dark blue button read "Download All Files"
