### ISSUE TITLE
Update localization text

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#53]
Update static text found in `config/locales/sufia.en.yml`

**Comment by grosscol** [comment]
Made a branch for this.  Could even do this work using github's interface as long **as you're on the edit_locales_text branch.**  Don't edit directly on master.

Here's a convenient link for you.
https://github.com/mlibrary/umrdr/blob/edit_locales_text/config/locales/sufia.en.yml

**Comment by jrcarlso9** [comment]
Reviewed this on Feb 11. made changes but had some questions as well. Let me know how you would like to proceed.

**Comment by grosscol** [comment]
@jrcarlso9 you have a few options.

1. Use github's in browser editor and commit the updates directly to the edit_locales_text branch.  The link in the comment above will bring you to the file on that branch.
2. Make edits locally using a text editor and we'll push the changes up to the edit_locales_text branch.

Then ping me when you are satisfied and want to merge the changes into the master branch.

**Comment by jrcarlso9** [comment]
I'm done. Please take a look and then merge changes into the master branch when ready.

**Comment by njaffer** [comment]
@jrcarlso9: Thank you, Your changes are on master branch. I will close this issue as done
