### ISSUE TITLE
setup redis name space

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#537]
## Background or Context
reported by @skorner: I can confirm with certainty that the resque/redis boundary is not set right in the currently deployed sufia instances on nectar OR it is not working as intended. I started up "training" with the extra resque logging, issued file deletes on a work of mine in staging via the staging web UI, and sometimes I saw the training resque pool processing the request.

**Comment by billdueber** [comment]
First notes: it looks like the systemd restart script actually already sets an appropriate environment variable: `REDIS_NS`. There are a couple places in our code where it might go (as determined by looking at the relevant heliotrope code), so I'll try to suss them out.

**Comment by billdueber** [comment]
More notes.

* There used to be a config/initializers file called `curation_concerns.rb` that set this. Those entries seem to have been folded into `sufia.rb`. This is referenced in #302 when things are changed to use the ENV variable `REDIS_NS` in that (now missing) file.
* Current `sufia.rb` tries to set namespace with `config.redis_namespace = Settings.redis_namespace`
* `redis_namespace` is set to "umrdr-staging" in `config/settings/production.yml`

...but it doesn't look like it's actually being set anywhere.

**Comment by billdueber** [comment]
Looks at redis (via `redis-cli`) shows a bunch of keys in there with various levels of naming:

```
1777) "events:93"
1778) "umrdr-staging:events:285"
1779) "FileSet:gx41mh844:event"
1780) "sufia:events:229"
1781) "sufia:events:38"
1782) "umrdr-staging:events:73"

```

So, sometimes `umrdr-staging`, sometimes `sufia`, and sometimes nothing at all.

Note to self: cli interative mode `KEYS` command to see recent keys. `redis-cli --scan  | head -10` to see the last 10 made
