### ISSUE TITLE
Update and Test Contact form 

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#54]
Test 'Contact Form' to see if the support person is getting the emails

**Comment by amyneeser** [comment]
Change e-mail from researchdataservices@umich.edu to deepblue@umich.edu. Also, can the subject on the form be auto populated as "Deep Blue Data"?

**Comment by grosscol** [comment]
Additionally the agreement.html should be updated.  If possible, update it to use text found in the appropriate locales or config.

**Comment by blancoj** [comment]
I'm trying to work on this one.  @amyneeser did you actually fill out the contact form and successfully send out an email.  I keep getting: "Sorry, this message was not delivered."

Also I don't see where the email was configured to be researchdataservices@umich.edu.

**Comment by amyneeser** [comment]
I have not tried to fill out the form.

I am not sure where it was originally configured; the UX team asked me
where the e-mail should go and we have changed our minds since then.

On Thu, Feb 18, 2016 at 11:22 AM, blancoj <notifications@github.com> wrote:

> I'm trying to work on this one. @amyneeser <https://github.com/amyneeser>
> did you actually fill out the contact form and successfully send out an
> email. I keep getting: "Sorry, this message was not delivered."
>
> Also I don't see where the email was configured to be
> researchdataservices@umich.edu.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlibrary/umrdr/issues/54#issuecomment-185800280>.
>



-- 
Amy Neeser
Research Data Curation Librarian
University of Michigan Libraries
260E Hatcher Graduate Library South
734-764-2203 | aneeser@umich.edu
ORCID: 0000-0003-2523-5079 <http://orcid.org/0000-0003-2523-5079>

**Comment by blancoj** [comment]
Thanks Amy.  It was not working, but I just figured it out.

**Comment by amyneeser** [comment]
You rock! Thanks.

On Thu, Feb 18, 2016 at 11:54 AM, blancoj <notifications@github.com> wrote:

> Thanks Amy. It was not working, but I just figured it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlibrary/umrdr/issues/54#issuecomment-185813611>.
>



-- 
Amy Neeser
Research Data Curation Librarian
University of Michigan Libraries
260E Hatcher Graduate Library South
734-764-2203 | aneeser@umich.edu
ORCID: 0000-0003-2523-5079 <http://orcid.org/0000-0003-2523-5079>

**Comment by njaffer** [comment]
change reply-to field to user's email address instead of deep-blue@umich.edu
