### ISSUE TITLE
RDS can view draft deposits

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#549]
## Background or Context
Is there a way that RDS can get a report of draft deposits or see them somehow?

**Comment by njaffer** [comment]
@amyneeser: The notification email at deposit time has this information. Please confirm.

**Comment by amyneeser** [comment]
@njaffer What information? I got this from a deposit yesterday: 

<img width="702" alt="screen shot 2017-01-16 at 11 02 11 am" src="https://cloud.githubusercontent.com/assets/3106478/21990059/5934fe92-dbdb-11e6-80f3-2ffe4bc099d3.png">

**Comment by njaffer** [comment]
ok it is not in production. Let me do a test one on staging.

**Comment by amyneeser** [comment]
This looks great! 

<img width="701" alt="screen shot 2017-01-16 at 12 19 17 pm" src="https://cloud.githubusercontent.com/assets/3106478/21992857/128e88fe-dbe6-11e6-8786-84f2f4ac3fb5.png">

**Comment by njaffer** [comment]
Great!
