### ISSUE TITLE
Controlled Vocab for Subject property

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#55]
List of values accepted for subject field.
Dependent on #7

**Comment by amyneeser** [comment]
Amy, Jake C. Matt C. and Ben are meeting about this tomorrow afternoon (2/11).

**Comment by njaffer** [comment]
It was dependent on #7, which  is closed, is there any update on this one @bnhowell?

**Comment by njaffer** [comment]
closed with #73
