### ISSUE TITLE
Bug on deposit form: Citation to related material

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#570]
## Background or Context

Text for "add another citation..." cuts off: 

<img width="920" alt="screen shot 2017-01-06 at 10 51 54 am" src="https://cloud.githubusercontent.com/assets/3106478/21723584/fdb1a5ea-d3fe-11e6-9b71-4bc0fd76b2c9.png">

**Comment by amyneeser** [comment]
We tested this and it is only a problem on Safari (Chrome and Firefox work ok). We should still fix.

**Comment by jonearley** [comment]
https://github.com/mlibrary/umrdr/blob/26db810889da131e2c16bd70bf04523336dec16a/app/assets/stylesheets/custom_layout/tweaks.css#L16

Remove this styling that applies `width: 15em` and this will be fixed.
