### ISSUE TITLE
Redeployment script

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#597]
## Background or Context
Currently, only one person can deploy on staging and production. 

## Desired Behavior/Capability
Modify the deployment script so that multiple team members can deploy

**Comment by botimer** [comment]
I think the last remaining issue here is that the TinyMCE asset installer tries to preserve file attributes when copying, which breaks if there is a different owner.

~~~
#bundle/ruby/2.3.0/gems/tinymce-rails-4.4.1/lib/tinymce/rails/asset_installer/copy.rb
#...
        def copy_assets
          logger.info "Copying assets to #{File.join(target, "tinymce")}"
          FileUtils.cp_r(assets, target, :preserve => true)
        end
~~~
