### ISSUE TITLE
Repurpose single use links for alt preservation strategy

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#60]
While excising/overriding single use links for #44, keep functionality around.  Could be used as an alternative level of preservation.  The code path and strategy could be used as a gateway into a cache drawn from low cost long term storage for less apparently valuable material.

`single_use_link request -> retrieve/prepare -> cache -> notify -> download|expire -> remove cached`

**Comment by amyneeser** [comment]
We will remove single use links for the time being and revisit when we enable embargo functionality.
