### ISSUE TITLE
Display Contact Information

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#600]
## Background or Context
Exists in Sufia, we removed it from umrdr

**Comment by blancoj** [comment]
In Hyrax this is shown in the list of works, but on the work page nothing about the depositor and owner is shown.  I could change RDR to show depositor and owner on the work page.  Also, not sure if it should be a link to profile page or just a text of the email.  What do you think @njaffer ?

<img width="1020" alt="screen shot 2017-02-10 at 11 44 00 am" src="https://cloud.githubusercontent.com/assets/11095558/22835391/8d397d4e-ef86-11e6-8b35-ce0e25918ae6.png">

**Comment by jakecarls** [comment]
I think we would want to know who the depositor is and so we should make this a part of the admin metadata, but I don't see any value in making the depositor a part of the public metadata record. I don't think it matters to a potential user who made the deposit. 

I also find the "owner" field confusing as I would not be sure how it differs from "creator". If the owner filed is meant to convey contact information for someone to get more information about the data I think we should just call it contact information. 

If we do add contact information as a metadata field we need to contact Matt Carruthers to ask if there is a standard way to represent this type of information.

**Comment by amyneeser** [comment]
I agree. Let's add a metadata field: contact information 

Help text: The contact information for individual who can best respond to questions about this dataset.

**Comment by njaffer** [comment]
@amyneeser @jakecarls: Deep Blue has a metadata field, contributor.authoremail (DC.contributor.authoremail). We can add that, and you will have the email address of the author. Do you want to save any other contact info or just email is good?

**Comment by jakecarls** [comment]
Amy and I had talked about opening the field up to include a phone number,
but upon reflection I don't think that makes sense. Let's just stick with
email contact info and use the DC metadata field that you have identified.
Thanks.

-Jake

**Comment by amyneeser** [comment]
@njaffer As far as we can tell, this is resolved on our end. Let us know if you need something else from us.
