### ISSUE TITLE
Test feasibility of adding Full Text Extraction feature

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#609]
## Background or Context
related to #16 and #42

**Comment by amyneeser** [comment]
Use case: I am working with some researchers (e.g. Monnier) who have more useful metadata baked in to their actual data than can be captured in our metadata. So we'd want to index those.

**Comment by amyneeser** [comment]
If possible, we'd like to explore indexing certain file types but not others (e.g. .txt, .PDF)
