### ISSUE TITLE
Batch ingest request: Barto 3/7/17

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#612]
## Background or Context

This researcher has given us NFS access to his data. The path is: shore.engin.umich.edu:/volume1/UMFORDAVDATA and the data lives in the PASCAL folder under that.

@blancoj can you ingest this into Deep Blue Data? I am waiting for him to give me the metadata. 

This is the command to run to ingest the Barto data

RAILS_ENV=production bundle exec rake umrdr:populate[/hydra-dev/umrdr-data/barton/data.yml]

**Comment by amyneeser** [comment]
Here's the metadata: 

[DeepBlueData_metadata_Barto.xlsx](https://github.com/mlibrary/umrdr/files/828388/DeepBlueData_metadata_Barto.xlsx)

**Comment by blancoj** [comment]
@amyneeser I was just circling back to this.  I think we are waiting for the researcher to identify the files he wants in the repository, since there are so many, AND also we need to determine how to deal with the cc license he has, since it is one that we presently don't have in our list.  Just wanted to document this before I forget.

**Comment by amyneeser** [comment]
I e-mailed the depositor on 4/6 asking for an update and have not gotten a response yet.

**Comment by amyneeser** [comment]
Charlie replied: 

OK I've copied the archives of our dataset to the DeepBlue directory on the NAS. You can scoop up everything in there. I've also created a readme.md file in that directory that's a copy of our paper's code release readme with some images removed (to make it text only).

@blancoj do you have what you need to start the ingest now?

**Comment by billdueber** [comment]
These files have been copied to local storage at `/hydra-dev/umrdr-data/barton/DeepBlue/`

**Comment by blancoj** [comment]
The code was changed to not do virus checking for files greater than 4G, and so we were able to upload the dataset as private.  Once @amyneeser will make it public when she's happy with it.
https://deepblue.lib.umich.edu/data/concern/generic_works/pv63g053w
