### ISSUE TITLE
Batch ingest request: Carson 3/16/2017

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#618]
## Background or Context

Please delete the data attached to this deposit: https://deepblue.lib.umich.edu/data/concern/generic_works/9g54xh64n

And load the data in these folders: https://drive.google.com/drive/folders/0BxumEmZ6w7aVY2JKMTZIdFBKNzQ

Let's leave the folders uncompressed unless they are bigger than 2GB.

**Comment by blancoj** [comment]
Done https://deepblue.lib.umich.edu/data/concern/generic_works/9g54xh64n
