### ISSUE TITLE
Metadata update request: James, 3/22/2017

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#621]
## Background or Context

For this work: https://deepblue.lib.umich.edu/data/concern/generic_works/ft848q70w

Please change the text in the "citation to related material" field to the following: The paper, Symmetry in European Folk Costumes, that analyzes the data in the spreadsheet and Access Database can be found at: 
http://hdl.handle.net/2027.42/136161

**Comment by blancoj** [comment]
Done.
