### ISSUE TITLE
Update files: Hu 3/25/2017

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#624]
## Background or Context

For work gb19f5810: 

1. Delete all the files except one. They are duplicates. 
2. Add attached files: readme.txt, tornado_complete.txt, report.pdf

[READ_ME.txt](https://github.com/mlibrary/umrdr/files/871129/READ_ME.txt)
[Report.pdf](https://github.com/mlibrary/umrdr/files/871127/Report.pdf)
[tornado_complete.txt](https://github.com/mlibrary/umrdr/files/871128/tornado_complete.txt)

**Comment by blancoj** [comment]
@amyneeser this is all set.
