### ISSUE TITLE
Delete attached files and point to Deep Blue: Rowe, 4/4/17 

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#628]
## Background or Context
This user made a [deposit in Deep Blue Data](https://deepblue.lib.umich.edu/data/concern/generic_works/mk61rg99w), but decided he wants his videos streaming so it has been moved to Deep Blue. However, he minted a DOI and we do not have a procedure in place for making tombstones. 

## Desired Behavior/Capability
Please remove the files and point to the [Deep Blue record](https://deepblue.lib.umich.edu/handle/2027.42/136202) in the related files section.

**Comment by blancoj** [comment]
@amyneeser take a look at this:  https://deepblue.lib.umich.edu/data/concern/generic_works/mk61rg99w

I don't think there is any harm in leaving the files in there.  Let me know what you think.

**Comment by njaffer** [comment]
1. Remove attached files from DBD
2. Change DO target URL to the deep blue link

**Comment by blancoj** [comment]
Files were deleted from Deep Blue Data record, and the doi was added to https://deepblue.lib.umich.edu/handle/2027.42/136202.  @skorner changed the DOI to point to the Deep Blue Doc record.
