### ISSUE TITLE
Indexing full text for search

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#642]

**Comment by njaffer** [comment]
test it with pdf, text, xls, doc

**Comment by njaffer** [comment]
@amyneeser: what other file types?

**Comment by amyneeser** [comment]
Please also test a FITS file from the Monnier data on training.

**Comment by blancoj** [comment]
This is the kind of fulltext extraction that happens in hyrax:

https://github.com/samvera-labs/hyrax/blob/master/app/services/hyrax/file_set_derivatives_service.rb#L22

Here is the code, in case the code above changes.
    def create_derivatives(filename)
      case mime_type
      when *file_set.class.pdf_mime_types             then create_pdf_derivatives(filename)
      when *file_set.class.office_document_mime_types then create_office_document_derivatives(filename)
      when *file_set.class.audio_mime_types           then create_audio_derivatives(filename)
      when *file_set.class.video_mime_types           then create_video_derivatives(filename)
      when *file_set.class.image_mime_types           then create_image_derivatives(filename)
      end
    end
