### ISSUE TITLE
move to Hyrax branch from sufia_7.3 branch - test out data migration on staging.

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#695]
Staging should have records created based on the master code (just like in prod), so it would be a good idea to test data migration to hyrax there. 
Here is what I see happening.

Note: This is where the upgrade documentation is at https://github.com/samvera-labs/hyrax/releases

- [x]  Make sure staging has master running.
- [x]  Make sure you have a few works and collections on staging.
   Used command like this one:
    - [x] [blancoj@nectar:/hydra-dev/umrdr-staging/current]# RAILS_ENV=production bundle exec rake umrdr:populate[/hydra-dev/dspace-data/archive/100/data.yml]
   - [x] I created a collection ("Jose's collection" 
 https://staging.deepblue.lib.umich.edu/data/collections/7d278t32v with 6 works 
   - [x] I created another collection with 8 works - "Another Collection" https://staging.deepblue.lib.umich.edu/data/collections/4j03cz98q- [ ]   Make sure master is working well on staging.
- [x]   Release the hyrax code on staging.
- [x]  Setup the default admin set:
    RAILS_ENV=production bundle exec rake hyrax:default_admin_set:create
- [x] Make sure workflow is attached to default admin set
- [x]  Now it's time to run the data migration script developed my hackmaster.  From /hydra-dev/umrdr-staging/current run this command:
  - [x] RAILS_ENV=production bundle exec rake hyrax:migrate:collections
  - [] RAILS_ENV=production bundle exec rake hyrax:migrate:move_all_works_to_admin_set

**Comment by njaffer** [comment]
Training instance is updated with hyrax branch
