### ISSUE TITLE
hyrax - can start building support for globus

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#734]
It can work just like "Download All".  We'll need to email the user once the dataset is at the file location.  The email will contain the name of the "directory" from were the dataset can be accessed.  The email will also let the user know how long the the dataset will be available from that end point.  @amyneeser  and Jake seemed interested in being able to select individual bitstreams from the list of files to send to Globus.  We can start building all this functionality without having Globus in place, since all we need to do is put the file in some dir and let the user know when the files are all moved from Fedora to that location.

- [ ] Has "Download All for Globus" button (in app/views/hyrax/base/_related_files.html.erb)
- [ ] Button submit action copies work's files into a /tmp directory (globus action in app/controllers/hyrax/generic_works_controller.rb)
- [ ] Globus directory set for nectar or an env variable:
    globus_dir = ENV['GLOBUSDIR'] || "/hydra-dev/umrdr-data/globus"
    folder = globus_dir + "/DeepBlueData_" + curation_concern.id

**Comment by mutanthumb** [comment]
Hi, I was wondering if ND API for "Tape Manager" might work in this scenario? 
From Donald Brower @ ND during Vitrual Connect: Here is the link to the actual tape manager. https://github.com/ndlib/bendo  The samvera app only uses a subset of the API, something like "is file cached?", "cache file", and "get file". FWIW from Nathan Tallman: +1 to integrating Globus via abstracted tape manager! I think PSU might be interested.

**Comment by skorner** [comment]
@mutanthumb That is a very appealing idea. In fact, I only noticed your comment when I opened this issue to remind folks that whatever you build into the app also needs to check if the content already exists in the Globus staging area before initiating an extract (i.e. don't overwrite it with the same content). Existing code that already handles the logic and edge cases of content staging is compelling.

**Comment by gordonleacock** [comment]
Hi @mutanthumb - How would I know if the repository files for the work have
changed?

Right now the code deletes any existing directory with the same name then
replaces it and adds the files. This seems like the safest course.

Glad to talk about this more... Gordon

**Comment by mutanthumb** [comment]
That's an excellent question @gordonleacock I'm not sure what RDS policy is around datasets changing after they have been officially submitted to the system. Let me check with @amyneeser and @jakecarls about this. 

Just to be clear are you talking about deleting files from cache or Fedora itself? BTW, is there versioning with Fedora Samvera?

**Comment by gordonleacock** [comment]
I'm talking about deleting directories and files written out to a special globus directory. One set up to enable transfers to globus endpoints. Unless I'm misunderstand the purpose of the globus code?

**Comment by gordonleacock** [comment]
My added code doesn't touch internal application storage except to retrieve files for export from a work.

**Comment by mutanthumb** [comment]
I'm guessing there is not "nice" way to tell whether the data has changed or not. I'm just thinking it would be quicker for the end user if they didn't have to wait for the file(s) to be copied again to the cache.

**Comment by gordonleacock** [comment]
@mutanthumb - I guess this also raises the question: Do we need a "progress bar" or other indicator that transfers are happening. But we can burn that bridge when we get to it (joke!).

**Comment by mutanthumb** [comment]
@gordonleacock yes I think that would be great idea (sans bridge of course) or perhaps an estimated time of availability? I was also thinking it would be good to provide total file size and number of files to the end user so they have some idea what they are getting into.

**Comment by skorner** [comment]
+1 to what @mutanthumb wrote about providing the user with estimates. A progress or status bar is tricky given the expectation is that the user initiates the request, "walks away", and receives an email when staging is complete. That could be a day or more in a worst case scenario. Also, that's ignoring any complexity on the app side with regards to monitoring the extract for real-time progress.

Regarding the logic of "replace if it already exists" that @gordonleacock started with, that's maybe an OK first pass solution. However, it has a failure mode of:
1. user A requests dataset X
2. dataset X is staged and user A is notified
3. user A beings globus download of dataset X
4. user B requests dataset X
5. dataset X is wiped from staging while user A is downloading it and a new transfer begins
6. user A is confused and unhappy

This can be solved by staging each request with the username as part of the directory name, but then we are really in the wasting space world.

A more sophisticated answer might be to place a flag in the staged dataset (e.g. a file called .complete at the root) after the transfer completes. This flag could then be used for multiple purposes to manage race conditions and to check whether a refresh is needed or not upon a subsequent request.

**Comment by jakecarls** [comment]
It looks like you've moved on from the "changing data sets once they've been submitted" discussion, but to answer the question posed by @mutanthumb DBD policy is not to allow changes to the data once it has been submitted, with rare exception. Instead, changes to a data set would be made into a new and separate deposit, that could be linked to the original deposit if needed (new version, etc.).

**Comment by gordonleacock** [comment]
Thanks @skorner, @mutanthumb, and Jake - I will keep these improvements in
mind.

**Comment by gordonleacock** [comment]
Changes made as recommended above. Globus button is hidden for now in prep for production hyrax.
