### ISSUE TITLE
hyrax - deposit errors out when sending email

### ISSUE THREAD

**Issue by blancoj** [mlibrary/umrdr#744]
In training, if you deposit a work it tries to send an email, and it blows up  at line 28 of app/controller/hyrax/generic_works_controller.rb when it tries to send an email.  I have commented that line out on training so it will not blow up for now.  I believe it gets the email from /hydra-dev/umrdr-deploy/upload/training-config/settings/production.yml.  In this file there is this setting: `umrdr_host: "training.deepblue.lib.umich.edu"` it used to say `umrdr_host: "staging.deepblue.lib.umich.edu"`.  I changed it from staging to training thinking that was the issue, but no change.  That's all I know.  Does it make sense for you to look at this?  Thanks! Jose

**Comment by njaffer** [comment]
@billdueber: Can you please update this ticket.

**Comment by gordonleacock** [comment]
I think the .yml files in config/settings have to be setup for email to work correctly based on what I saw with globus. Specifically these lines:
```# Settings for email contact form and deposit notification
contact_email: <%= "#{ENV['USER']}@umich.edu" %>
from_email: 'deepblue@umich.edu'
notification_email: <%= "#{ENV['USER']}@umich.edu" %>```

**Comment by njaffer** [comment]
It works on staging and is not working on training
