### ISSUE TITLE
Create collection (something went wrong error) in training

### ISSUE THREAD

**Issue by fritzfreiheit** [mlibrary/umrdr#745]
## Background or Context
Attempting to create a collection when no other collections exists  (I did successfully create two works).

## Desired Behavior/Capability
Should create a collection

## Existing Behavior/Capbility
Returns error page.

## Steps to reproduce or demonstrate

Attempting to create a collection when no other collections exists  (I did successfully create two works):

https://training.deepblue.lib.umich.edu/data/dashboard/collections?locale=en

Clicked on: "New Collection" button

Returned a page:

https://training.deepblue.lib.umich.edu/data/collections/new?locale=en

With:

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

**Comment by fritzfreiheit** [comment]
Error trace from logs (a fatal error):
ActionView::Template::Error (undefined local variable or method `cur
ation_concern' for #<#<Class:0x0055d387a16458>:0x0055d38afe8e50>
Did you mean?  curation_concern_page_title):
F, [2017-06-27T14:13:40.769947 #18335] FATAL -- :     1: <% license = Hyrax::LicenseService.new %>
    2:
    3: <% if ((license.select_active_options.join(",").split(',').include? (curation_concern.rights[0])) || (curation_
concern.date_uploaded==nil) )%>
    4: <% options = license.select_active_options.dup %>
    5: <% else %>
    6: <% options = license.select_all_options.dup %>

**Comment by njaffer** [comment]
@blancoj: DO we still need to override the rights active/inactive status. Isn't it fixed upstream. This line is causing problems for creating collections: https://github.com/mlibrary/umrdr/blob/hyrax/app/views/records/edit_fields/_rights.html.erb#L3
