### ISSUE TITLE
Update licences available to CC0, CC-by and CC-by-NC only

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#75]
Change is to be according to policy.  Per @heidisb these are the least restrictive of the six CC licenses.

Additionally, do not provide a default.  Rights should already be a required field.  Verify this as well.

**Comment by amyneeser** [comment]
Can we include brief descriptions of the three licenses inline on the form? We probably shouldn't assume users will read the full docs (I realize this is a slippery slope, but license terms are a critical thing for users to understand).

**Comment by respinos** [comment]
@amyneeser, @justcolin - 

![image](https://cloud.githubusercontent.com/assets/537867/13579492/d8a1517a-e46b-11e5-91b6-fcfc713e3ae6.png)

(I can imagine that references to _you_ should be replaced with "contributor"?)

**Comment by amyneeser** [comment]
Please use you / your as it matches our other documentation.

On Mon, Mar 7, 2016 at 1:53 PM, respinos <notifications@github.com> wrote:

> @amyneeser <https://github.com/amyneeser>, @justcolin
> <https://github.com/justcolin> -
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/537867/13579492/d8a1517a-e46b-11e5-91b6-fcfc713e3ae6.png>
>
> (I can imagine that references to *you* should be replaced with
> "contributor"?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlibrary/umrdr/issues/75#issuecomment-193393330>.
>



-- 
Amy Neeser
Research Data Curation Librarian
University of Michigan Libraries
260E Hatcher Graduate Library South
734-764-2203 | aneeser@umich.edu
ORCID: 0000-0003-2523-5079 <http://orcid.org/0000-0003-2523-5079>

**Comment by justcolin** [comment]
@respinos: What does the HTML look like?

**Comment by respinos** [comment]
In sort-of-Slim fashion:

```
div.form-group
  label "Creative Commons License"
  div.radio
    p
      label for="cc0"
        input type=radio value="cc0"
        "CC0 1.0 Universal"
     blockquote "Brief about CC0"
  ...
  p.help-block "Depositors must choose..."
```

The `blockquote` does have a certain *1999* feel to it. What would you recommend? `p.help-block` seemed the wrong option.

**Comment by justcolin** [comment]
It isn't really a quote, so I think `blockquote` isn't semantic. `p` is a fine cheat. `aside` might also work.

**Comment by grosscol** [comment]
Split out the UI request into #226
So the UI work for adding the description can be accomplished separately.
