### ISSUE TITLE
Upload Monnier Data

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#754]

**Comment by amyneeser** [comment]
Mounted at /mnt/monnier on nectar. Let A&E know when you're done with it - thanks!

**Comment by billdueber** [comment]
Directories `MIRC_2006Aug/2006Sep01` and 
`MIRC_2006Aug/2006Aug30` have been copied to local storage at 
`/hydra-dev/umrdr-data/monnier/`

**Comment by blancoj** [comment]
The two works associated with this request are now in production.
