### ISSUE TITLE
Add Amy and Jake and Moses and as admin

### ISSUE THREAD

**Issue by billdueber** [mlibrary/umrdr#755]

**Comment by njaffer** [comment]
@amyneeser, @moseshll : are you added as admin? can this be closed??

**Comment by amyneeser** [comment]
I'm not sure, how can I test to see?

**Comment by njaffer** [comment]
can you access /admin ?

**Comment by moseshll** [comment]
I'm not able to access /admin on staging or production. I am able to do so
in my local install.

**Comment by amyneeser** [comment]
Mine is not working.

**Comment by blancoj** [comment]
I've made all these users    
 - aneeser@umich.edu
 - jakecar@umich.edu
 - moseshll@umidh.edu

admins in training, which contains the hyrax branch.
