### ISSUE TITLE
Reconcile the about, terms, and agreement static documents

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#76]
@amyneeser @heidisb and the policy group might be good for this one.

relevant files are:
`app/views/static/about.html.erb`
`app/views/static/agreement.html`
`app/views/static/terms.html.erb` **needs to be copied from sufia in order to override**

These can be found at the relative urls:
`/data/about`
`/data/agreement`
`/data/terms`

**Comment by amyneeser** [comment]
Reviewed with @heidisb and e-mailed changes to @justcolin
