### ISSUE TITLE
Issue opening or viewing details of *.csv 

### ISSUE THREAD

**Issue by mutanthumb** [mlibrary/umrdr#765]
## Background or Context
Could not open or view details of *.csv:
https://training.deepblue.lib.umich.edu/data/concern/generic_works/j098zb08p?locale=en

## Desired Behavior/Capability
Would like to be able to open and view details of *.csv files in DBD. 

## Steps to reproduce or demonstrate
Just click on the csv file in https://training.deepblue.lib.umich.edu/data/concern/generic_works/j098zb08p?locale=en and you will get the error message.

**Comment by mutanthumb** [comment]
Verified that my *.csv is okay, from the desktop folder it opens just fine in Excel/Text Wrangler.

**Comment by mutanthumb** [comment]
Sorry, I inadvertently closed this issue.

**Comment by njaffer** [comment]
@mutanthumb: can you email me the csv, I want to try it on my local instance

**Comment by mutanthumb** [comment]
https://jira.duraspace.org/browse/FCREPO-2516?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=56178#comment-56178

**Comment by mutanthumb** [comment]
https://jira.duraspace.org/browse/FCREPO-2420

**Comment by mutanthumb** [comment]
discussed this with @botimer A&E are looking into this.

**Comment by Treevore** [comment]
Sorry was showing Github functionality for another project, please ignore my changes!

**Comment by skorner** [comment]
As we discussed in the meeting yesterday, if someone could compare the metadata for a csv that can be downloaded vs. one that can't, that would be informative. Of course, regardless of that outcome the remediation plan is a Fedora upgrade to 4.7.4 ASAP.

**Comment by mutanthumb** [comment]
This csv works: https://deepblue.lib.umich.edu/data/concern/generic_works/2f75r8102
This one does not: https://deepblue.lib.umich.edu/data/concern/generic_works/gx41mh96x
