### ISSUE TITLE
could not create "New Collection"

### ISSUE THREAD

**Issue by mutanthumb** [mlibrary/umrdr#766]
## Background or Context
Tried to create a new collection as part of testing and received an error message. This happened during testing of https://training.deepblue.lib.umich.edu/data/

## Steps to reproduce or demonstrate
Clicked on the "New Collection" under "My Collections" and recieved message "We're sorry, but something went wrong."

https://training.deepblue.lib.umich.edu/data/collections/new?locale=en

**Comment by njaffer** [comment]
can be closed with merging of PR #746
