### ISSUE TITLE
Odd message indicating that I had "changed the access level..." when I had just changed the Method

### ISSUE THREAD

**Issue by mutanthumb** [mlibrary/umrdr#767]
## Background or Context
During testing of training version, I changed the "Method" field of the work and was given an odd/confusing confirmation message.

## Desired Behavior/Capability
Wording on confirmation message should match the change that was made.

## Steps to reproduce or demonstrate
After editing the "Methods" field and click on "Publish" I was given this message: 
"You have changed the access level on work New ugly data, making it accessible to other users or groups to view or edit.
Would you like change all of the files within the work to have the same access users, groups and visibility as well?"  

---My change had nothing to do with Access.
 After choosing to "Update Manually" the wording change to Methods was processed.

**Comment by njaffer** [comment]
@mutanthumb: Did you create the work as draft, the first time?

**Comment by njaffer** [comment]
<img width="1139" alt="screen shot 2017-07-07 at 3 53 52 pm" src="https://user-images.githubusercontent.com/12487929/27974590-a6895b56-632c-11e7-9ad7-322c3e3af832.png">
