### ISSUE TITLE
Date Coverage property for works

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#78]
Important metadata property describing the temporal range addressed by the work.
- [x] Metadata librarian finding appropriate predicate
- [x] UX design
- [x] UI implementation

related: discover-ability of date ranges.

**Comment by grosscol** [comment]
Complicating Date and Temporal coverage representation is weather to stuff a date range into a single string.  Such is the case for https://github.com/dpla/rdf-edtf which will likely be our first pass.  Which would require any other institution or application reading that field to also implement the edtf logic.

The more semantic web way would be to have one or more time span nodes each with their own start and end properties.  The discussion on the hydra-tech google group was informative:

> Such ranges will usually come to us in a series of date fields, which will each get mapped to a TimeSpan. the range would then be extracted out. Something like:
> 
>   <#sourceResource> dct:date [ 
>     a edm:TimeSpan ;
>     dpla:providedLabel "2016" .
>     edm:begin "2016-01-01"^^lc:edtf ;
>     edm:end "2016-12-31"^^lc:edtf .
>   ],
>   [ a edm:TimeSpan ;
>     dpla:providedLabel "2011 to 2012" .
>     edm:begin "2011-01-01"^^lc:edtf ;
>     edm:end "2012-12-31"^^lc:edtf .
>   ] .

Related to #313

**Comment by njaffer** [comment]
done
