### ISSUE TITLE
Change Collection visibility to private

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#796]
## Background or Context
https://deepblue.lib.umich.edu/data/collections/tm70mv312

**Comment by amyneeser** [comment]
There are several collections we would like to make private. Let's test this one to see if it cane work and if it does I'll send along the IDs of the other collections.

**Comment by njaffer** [comment]
I just made it private. Please check and then I can make the rest private too

**Comment by amyneeser** [comment]
please hide and give jakecar, sborda, and aneeser access to these collections: 

collections/6969z104t
collections/5q47rn869
collections/jm214p29x
collections/8623hx85s
collections/05741r82t
collections/4b29b6164
collections/3197xm18w
collections/9z903006b
collections/00000021r
collections/r207tp45g
collections/5999n3499
collections/2514nk65p
collections/5t34sj73g
collections/z316q169v
collections/vm40xr69n
collections/pz50gw33g
collections/nz805z83t
collections/4j03cz86x
collections/d217qp55z
collections/cj82k743r
collections/ns0646175
collections/0z708w64z
collections/5712m6702
collections/tt44pm96f
collections/1544bp23h
collections/k643b134k
collections/8336h2025

**Comment by fritzfreiheit** [comment]
# ruby script to perform update
ids_wanted = ['6969z104t','5q47rn869','jm214p29x','8623hx85s','05741r82t','4b29b6164','3197xm18w','9z903006b','00000021r','r207tp45g','5999n3499','2514nk65p','5t34sj73g','z316q169v','vm40xr69n','pz50gw33g','nz805z83t','4j03cz86x','d217qp55z','cj82k743r','ns0646175','0z708w64z','5712m6702','tt44pm96f','1544bp23h','k643b134k','8336h2025']
c_selected = Collection.find_all { |e| ids_wanted.include? e.id }
c_selected.map { |e| e.visibility } # for display of state before
c_selected.each { |e| e.visibility = 'restricted'; e.save }
c_selected.map { |e| e.visibility } # for display of state after

**Comment by fritzfreiheit** [comment]
ids_wanted = ['6969z104t','5q47rn869','jm214p29x','8623hx85s','05741r82t','4b29b6164','3197xm18w','9z903006b','00000021r','r207tp45g','5999n3499','2514nk65p','5t34sj73g','z316q169v','vm40xr69n','pz50gw33g','nz805z83t','4j03cz86x','d217qp55z','cj82k743r','ns0646175','0z708w64z','5712m6702','tt44pm96f','1544bp23h','k643b134k','8336h2025']
c_all = Collection.all
c_selected = c_all.select { |e| ids_wanted.include? e.id }
c_selected.map { |e| e.visibility } # for display of state before
c_selected.each { |e| e.visibility = 'restricted'; e.save }
c_selected.map { |e| e.visibility } # for display of state after

**Comment by fritzfreiheit** [comment]
@amyneeser -- Production has been updated. Do you want to take a look at some (or all) of the records? I'll close the ticket if you're satisfied.

**Comment by fritzfreiheit** [comment]
@amyneeser -- Sorry, I forgot to add the permissions. I'll do that.

**Comment by fritzfreiheit** [comment]
ids_wanted = ['6969z104t','5q47rn869','jm214p29x','8623hx85s','05741r82t','4b29b6164','3197xm18w','9z903006b','00000021r','r207tp45g','5999n3499','2514nk65p','5t34sj73g','z316q169v','vm40xr69n','pz50gw33g','nz805z83t','4j03cz86x','d217qp55z','cj82k743r','ns0646175','0z708w64z','5712m6702','tt44pm96f','1544bp23h','k643b134k','8336h2025']
c_all = Collection.all
c_selected = c_all.select { |e| ids_wanted.include? e.id }
c_selected.map { |e| e.edit_users } # for display of state before

c_selected2 = c_selected.select { |e| !e.edit_users.include?( "aneeser@umich.edu" ) }
c_selected2.each { |e| e.edit_users += ["aneeser@umich.edu"]; e.save }
c_selected2.map { |e| e.edit_users }

c_selected2 = c_selected.select { |e| !e.edit_users.include?( "sborda@umich.edu" ) }
c_selected2.each { |e| e.edit_users += ["sborda@umich.edu"]; e.save }
c_selected2.map { |e| e.edit_users }

c_selected2 = c_selected.select { |e| !e.edit_users.include?( "jakecar@umich.edu" ) }
c_selected2.each { |e| e.edit_users += ["jakecar@umich.edu"]; e.save }
c_selected2.map { |e| e.edit_users }

**Comment by fritzfreiheit** [comment]
@amyneeser and @njaffer -- All set. Edit permissions added. When you get a chance, you can verify and I'll close the ticket.
