### ISSUE TITLE
Enforce 2GB limit for file uploads

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#80]
Needs to be a validation at the model level prior to save for the FileSet. This should be a safety net.
Needs to be baked into the UI (probably js widget)

**Comment by justcolin** [comment]
The size limit needs to be enforced server side. A warning can be added the the UI JS, but the server side check is the priority for the initial release.

**Comment by respinos** [comment]
The file upload plugin has a limitMultiFileUploadSize (see: https://github.com/blueimp/jQuery-File-Upload/wiki/Options), although curation_concern's `uploader.js` doesn't use it.

**Comment by justcolin** [comment]
@respinos: Thanks! I'll add that to our code.

**Comment by respinos** [comment]
Working on rejecting individual files over Sufia.config.max_file_size.
