### ISSUE TITLE
Cleanup of Help page

### ISSUE THREAD

**Issue by mutanthumb** [mlibrary/umrdr#808]
## Background or Context
https://deepblue.lib.umich.edu/data/help
This ticket goes along with #807 

## Desired Behavior/Capability

Should only have these sections:
- [x] Prepare Your Data
- [x] How to Upload
- [x] ~~Support for Depositors~~
- [x] Use Downloaded Data
- [x] Contact Us

## Existing Behavior/Capability

- About Deep Blue Data
- Prepare Your Data
- How to Upload
- File Formats & Preservation
- Retention
- Support for Depositors
- Use Downloaded Data
- Contact Us

**Comment by moseshll** [comment]
I note that "Support for Developers" is also included in "keep" list for the About page in #807. Is this duplication by design?

**Comment by mutanthumb** [comment]
"Support for Depositors" should only be in About. Thanks for catching that!
