### ISSUE TITLE
User request: Huang 8/15/2017

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#819]
Please make the following changes to deposit: xk81jk44d

delete all the files and upload the following:

[Simulation Parameters_Readme.txt](https://github.com/mlibrary/umrdr/files/1225386/Simulation.Parameters_Readme.txt)
[Simulation Parameters.xlsx](https://github.com/mlibrary/umrdr/files/1225387/Simulation.Parameters.xlsx)

Also add the following co-authors: 
Ming Huang, Wenjun Huang, Fei Wen, and Ronald G. Larson

**Comment by fritzfreiheit** [comment]
Done.
