### ISSUE TITLE
user request: Carson 8/15/2017

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#820]
For work 9g54xh64n attach the following readme file and put at the top of the files: 

[Cell Immuno CCL2 raw data - Readme.txt](https://github.com/mlibrary/umrdr/files/1225449/Cell.Immuno.CCL2.raw.data.-.Readme.txt)

**Comment by fritzfreiheit** [comment]
@amyneeser -- I've added the readme file, but it shows up last. The only way that I think I can put it at the top of the list is to remove all the files and then add them back in the desired order. Should I do this?

**Comment by mutanthumb** [comment]
@fritzfreiheit yes Fritz go ahead.

**Comment by fritzfreiheit** [comment]
Done.
