### ISSUE TITLE
Add alert for large file issue 

### ISSUE THREAD

**Issue by mutanthumb** [mlibrary/umrdr#821]
## Background or Context
We need to inform depositors that we cannot download files larger than 2GB. 

## Desired Behavior/Capability
This alert should be added to the "Deposit Work" page as well to the About page referencing file size: https://deepblue.lib.umich.edu/data/prepare-your-data to this bullet "For deposits exceeding 2 GB, we will work with depositors to ingest your data. Please contact us if your deposit exceeds 2 GB."

Here is the alert language:
8/16/2017 - We are currently implementing a solution for downloading large datasets. Until this solution is in place, we are not accepting files larger than 2GB. We will post updates as they become available. In the meantime, please feel free to contact [Research Data Services](mailto:deepblue@umich.edu) with any related questions or concerns, so your data will be ready to be deposited when our system is ready to go.

**Comment by fritzfreiheit** [comment]
See #854
