### ISSUE TITLE
RDS: Un-embargo Sifuentes Data on September 1

### ISSUE THREAD

**Issue by amyneeser** [mlibrary/umrdr#822]
There are 8 empty works bundled into the following collection: https://deepblue.lib.umich.edu/data/collections/j96020624

On September 1, we need to change the titles of these works to remove the message about embargo and upload the data files to the works. The data currently lives here: https://drive.google.com/open?id=0B1XrjyNAKCvmdmx4UHhmWUllWWs

@mutanthumb

**Comment by mutanthumb** [comment]
@fritzfreiheit 
generic_works/4b29b6007 - Appendix8.docx
generic_works/s1784k77h - Appendix7.pdf
generic_works/jq085j99x - Appendix6.xlsx
generic_works/w9505053x - Appendix5.xlsx
generic_works/x920fw90j - Appendix4.xlsx
generic_works/3484zh00p - Appendix3.xlsx
generic_works/vh53wv75j - Appendix2.xlsx
generic_works/nc580m674 - Appendix1.xlsx
[Appendix1.xlsx](https://github.com/mlibrary/umrdr/files/1270222/Appendix1.xlsx)
[Appendix2.xlsx](https://github.com/mlibrary/umrdr/files/1270223/Appendix2.xlsx)
[Appendix3.xlsx](https://github.com/mlibrary/umrdr/files/1270226/Appendix3.xlsx)
[Appendix4.xlsx](https://github.com/mlibrary/umrdr/files/1270224/Appendix4.xlsx)
[Appendix5.xlsx](https://github.com/mlibrary/umrdr/files/1270225/Appendix5.xlsx)
[Appendix6.xlsx](https://github.com/mlibrary/umrdr/files/1270227/Appendix6.xlsx)
[Appendix7.pdf](https://github.com/mlibrary/umrdr/files/1270228/Appendix7.pdf)
[Appendix8.docx](https://github.com/mlibrary/umrdr/files/1270229/Appendix8.docx)

**Comment by mutanthumb** [comment]
Uploaded the final file: Appendix1.xlsx 
The collection is here: https://deepblue.lib.umich.edu/data/collections/j96020624?locale=en
