### ISSUE TITLE
When editing, creator field is not correctly populated

### ISSUE THREAD

**Issue by fritzfreiheit** [mlibrary/umrdr#823]
## Background or Context
When editing, creator field is not correctly populated

## Desired Behavior/Capability
Creator field is populated by value in database

## Existing Behavior/Capbility
Creator field is populated with something like:
"#<ActiveTriples::Relation:0x00563e6f569100>"

## Steps to reproduce or demonstrate
Edit a work.

**Comment by mutanthumb** [comment]
This is also a problem on the Edit Collection screen.

**Comment by njaffer** [comment]
can be closed with PR from Fritz
