### ISSUE TITLE
Fix ordered_member_ids patches made to facilitate updating sufia and cc

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#85]
In order to update the Sufia and CurationConcerns dependencies in #81, app/forms/curation_concerns/forms/work_form.rb and app/presenters/sufia/file_set_presenter.rb were copied up to this project to override them.

A description of the problem encountered is here: projecthydra-labs/curation_concerns#625
Upstream issue or pull request forthcoming.

To resolve
- [ ] upstream fix is made.
- [ ] dependencies are updated to include upstream fix.
- [ ] overriding code is removed or trimmed to minimum required.

**Comment by grosscol** [comment]
Relevant upstream issue: projecthydra/sufia#1593

**Comment by njaffer** [comment]
Need to confirm if it is done upstream

**Comment by njaffer** [comment]
it is closed upstream
