### ISSUE TITLE
Logging out causes error?

### ISSUE THREAD

**Issue by justcolin** [mlibrary/umrdr#89]
I went to log out with the latest pull from master and got this:
![screen shot 2016-02-20 at 1 24 53 am](https://cloud.githubusercontent.com/assets/11234702/13194946/4a673d68-d771-11e5-94c3-a9c73ed81ca4.png)

**Comment by grosscol** [comment]
Good catch.  Oversight on my part with putting things behind cosign.  I'll have to sort out the cosign logout url.

**Comment by skorner** [comment]
You may have already found it, but if not logout looks like this:

https://weblogin.umich.edu/cgi-bin/logout?<return URL>

**Comment by grosscol** [comment]
Unlike login, the logout url doesn't require parameters and the back button is just the browser's back functionality.

**Comment by justcolin** [comment]
We still want the logout to dump people back to the UMRDR home
