### ISSUE TITLE
DOI Work

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#9]
Use EZID gem from hydra project for handling handle infrastructure.
Order of operations for minting DOIs will be:
1. Mint handle & point at repository resource.
2. Mint DOI to point at handle.

Publishing already does this.  Check with @aelkiss @jgmorse or @jmcglone regarding technical details of how these systems operate.

**Comment by aelkiss** [comment]
The EZID system does not deal directly with handles. My recommendation:

- Upgrade our handle infrastructure from 7.3.1 to 8.1
- Write a gem that uses the REST API available in Handle 8.1 to create handles:
 http://www.handle.net/tech_manual/HN_Tech_Manual_8.pdf chapter 14

**Comment by grosscol** [comment]
Use `dbd.` for the hdl prefixes per @skorner
