### ISSUE TITLE
Remove Visibility Link 

### ISSUE THREAD

**Issue by njaffer** [mlibrary/umrdr#97]
<img width="1280" alt="screen shot 2016-02-21 at 9 55 51 pm" src="https://cloud.githubusercontent.com/assets/12487929/13221144/d22197f8-d947-11e5-9fe3-1251f268fdd5.png">
<img width="1172" alt="screen shot 2016-02-21 at 9 54 03 pm" src="https://cloud.githubusercontent.com/assets/12487929/13221158/eacc36a0-d947-11e5-8182-810345bf4473.png">

**Comment by grosscol** [comment]
The actual link can be removed.  The Open Access text and styling are fine.  The alt text for the link can go with it as it is inaccurate.

**Comment by gordonleacock** [comment]
Just issued a PR for this - hopefully done now.

**Comment by justcolin** [comment]
I am still not seeing this change when I go to `/dashboard/works`, `/concern/generic_works/[work_id]`, etc.

@grosscol: has the PR from @gordonleacock not been pulled into master yet or did it not work?

**Comment by justcolin** [comment]
@njaffer Has this change been pushed to master? I am still not seeing it.

**Comment by njaffer** [comment]
yes I checked it.. I don't see the link any more. Can you please post a
screenshot where you see the link

**Comment by justcolin** [comment]
@njaffer On the My Works page there is still a Visibility column. It is no longer a link, but it is still there. If "Open Access" is the only option I would like to remove the column since it takes up valuable space and doesn't mean anything.

**Comment by njaffer** [comment]
Ok, this ticket was to remove the link only. If you want to remove the
'Open Access" label that would be fine. The scope of this ticket was not to
remove the full label, it was only to remove the link.
