### ISSUE TITLE
Add coverage property to GenericWork metadata

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#99]
Property to add is:
http://dublincore.org/documents/2000/07/11/dcmes-qualifiers/#coverage
Use RDF::Vocab for predicate.

**Comment by grosscol** [comment]
Specifically, this is temporal coverage:
http://dublincore.org/documents/dcmi-period/

**Comment by njaffer** [comment]
As per discussion with Amy, Jake, Matt C, the DC date_created will be used to save the date range
